"""Valuation Engine public API.

Additive engines:
* :meth:`ValuationEngine.analyze_dcf` — V1.2 DCF Intelligence
* :meth:`ValuationEngine.analyze_reverse_dcf` — V1.3 Reverse DCF
* :meth:`ValuationEngine.analyze_residual_income` — V1.4 Residual Income
* :mod:`valuation.core` — V1.5 Valuation Core Framework (infrastructure)
* :meth:`ValuationEngine.analyze_epv` — V1.6 Earnings Power Value
* :meth:`ValuationEngine.analyze_graham` — V1.7 Graham Intrinsic Value
* :meth:`ValuationEngine.analyze_ddm` — V1.8 Dividend Discount Model
* :meth:`ValuationEngine.analyze_asset_based` — V1.9 Asset-Based Valuation
* :meth:`ValuationEngine.analyze_relative` — V1.10 Relative Valuation Suite
* :meth:`ValuationEngine.analyze_consensus` — V1.11 Cross-Method Consensus
* :meth:`ValuationEngine.analyze_overall` — V1.12 Overall Valuation Aggregator
"""

from contracts.domain.margin_of_safety import MarginOfSafety
from valuation.asset_based import (
    ASSET_BASED_VERSION,
    AssetBasedEngine,
    AssetBasedInputs,
    AssetMethod,
    AssetQuality,
    AssetQualityFlag,
    AssetValuationResult,
    HaircutSchedule,
    to_valuation_result as to_asset_valuation_result,
    to_v2_aggregate_payload as to_asset_v2_aggregate_payload,
    validate_asset_based_inputs,
)
from valuation.assumptions import ValuationAssumptions
from valuation.consensus import (
    CONSENSUS_VERSION,
    CompanyProfile,
    ConsensusEngine,
    ConsensusInputs,
    ConsensusQualityFlag,
    ConsensusResult,
    ConsensusValidationError,
    MethodCategory,
    OutlierThresholds,
    WeightingMode,
    to_valuation_result as to_consensus_valuation_result,
    to_v2_aggregate_payload as to_consensus_v2_aggregate_payload,
    validate_consensus_inputs,
)
from valuation.core import (
    VALUATION_CORE_VERSION,
    ConfidenceEngine,
    ExplainabilityEngine,
    QualityFlag,
    ScenarioEngine,
    SensitivityEngine,
    ValidationEngine,
    ValuationMetadata,
    ValuationResult,
)
from valuation.dcf_intelligence import (
    CapmInputs,
    CapitalStructure,
    CostOfDebtInputs,
    DCF_INTELLIGENCE_VERSION,
    DcfAnalysisInputs,
    DcfBridgeInputs,
    DcfForecastAssumptions,
    DcfMarketInputs,
    DcfMosClassification,
    DcfSensitivitySpec,
    DcfTerminalAssumptions,
    DiscountedCashFlowEngine,
    DiscountedCashFlowResult,
    ExplainedValue,
    HistoricalFcfPoint,
)
from valuation.ddm import (
    DDM_VERSION,
    DdmEngine,
    DdmInputs,
    DdmMethod,
    DdmQualityFlag,
    DdmResult,
    DividendQuality,
    to_valuation_result as to_ddm_valuation_result,
    to_v2_aggregate_payload as to_ddm_v2_aggregate_payload,
    validate_ddm_inputs,
)
from valuation.engine import ValuationEngine
from valuation.enums import ValuationConfidence, ValuationMethod
from valuation.epv import (
    EPV_VERSION,
    EpvEngine,
    EpvInputs,
    EpvQualityFlag,
    EpvResult,
    NormalizationMethod,
    to_valuation_result as to_epv_valuation_result,
    to_v2_aggregate_payload as to_epv_v2_aggregate_payload,
    validate_epv_inputs,
)
from valuation.exceptions import ValuationError
from valuation.graham import (
    GRAHAM_VERSION,
    GrahamEngine,
    GrahamFormula,
    GrahamInputs,
    GrahamQualityFlag,
    GrahamResult,
    to_valuation_result as to_graham_valuation_result,
    to_v2_aggregate_payload as to_graham_v2_aggregate_payload,
    validate_graham_inputs,
)
from valuation.models import (
    IntrinsicValueEstimate,
    MarketSnapshot,
    ValuationAssessment,
    ValuationEvidence,
    ValuationRange,
)
from valuation.overall import (
    OVERALL_VERSION,
    MosClassification,
    MosThresholds,
    OverallEngine,
    OverallInputs,
    OverallQualityFlag,
    OverallValuationError,
    OverallValuationResult,
    ResearchLabel,
    to_valuation_result as to_overall_valuation_result,
    to_v2_aggregate_payload as to_overall_v2_aggregate_payload,
    validate_overall_inputs,
)
from valuation.relative import (
    RELATIVE_VERSION,
    BenchmarkMultiples,
    BenchmarkScope,
    RelativeEngine,
    RelativeInputs,
    RelativeMultiple,
    RelativeQualityFlag,
    RelativeValuationResult,
    StaticMultipleProvider,
    to_valuation_result as to_relative_valuation_result,
    to_v2_aggregate_payload as to_relative_v2_aggregate_payload,
    validate_relative_inputs,
)
from valuation.residual_income import (
    RESIDUAL_INCOME_VERSION,
    RESEARCH_DISCLAIMER,
    ResidualIncomeEngine,
    ResidualIncomeInputs,
    ResidualIncomeResult,
    ResidualIncomeScenario,
    RiQualityFlag,
    RoeForecastModel,
    to_v2_aggregate_payload,
    validate_residual_income_inputs,
    verify_clean_surplus,
    RiExplainedValue,
)
from valuation.reverse_dcf import (
    REVERSE_DCF_VERSION,
    ReverseDcfEngine,
    ReverseDcfInputs,
    ReverseDcfResult,
    ReverseDcfScenario,
    ReverseExplainedValue,
    validate_reverse_dcf_inputs,
)

__all__ = [
    "ASSET_BASED_VERSION",
    "AssetBasedEngine",
    "AssetBasedInputs",
    "AssetMethod",
    "AssetQuality",
    "AssetQualityFlag",
    "AssetValuationResult",
    "BenchmarkMultiples",
    "BenchmarkScope",
    "CONSENSUS_VERSION",
    "CapmInputs",
    "CapitalStructure",
    "CompanyProfile",
    "ConfidenceEngine",
    "ConsensusEngine",
    "ConsensusInputs",
    "ConsensusQualityFlag",
    "ConsensusResult",
    "ConsensusValidationError",
    "CostOfDebtInputs",
    "DCF_INTELLIGENCE_VERSION",
    "DDM_VERSION",
    "DcfAnalysisInputs",
    "DcfBridgeInputs",
    "DcfForecastAssumptions",
    "DcfMarketInputs",
    "DcfMosClassification",
    "DcfSensitivitySpec",
    "DcfTerminalAssumptions",
    "DdmEngine",
    "DdmInputs",
    "DdmMethod",
    "DdmQualityFlag",
    "DdmResult",
    "DiscountedCashFlowEngine",
    "DiscountedCashFlowResult",
    "DividendQuality",
    "EPV_VERSION",
    "EpvEngine",
    "EpvInputs",
    "EpvQualityFlag",
    "EpvResult",
    "ExplainabilityEngine",
    "ExplainedValue",
    "GRAHAM_VERSION",
    "GrahamEngine",
    "GrahamFormula",
    "GrahamInputs",
    "GrahamQualityFlag",
    "GrahamResult",
    "HaircutSchedule",
    "HistoricalFcfPoint",
    "IntrinsicValueEstimate",
    "MarginOfSafety",
    "MarketSnapshot",
    "MethodCategory",
    "NormalizationMethod",
    "OVERALL_VERSION",
    "OutlierThresholds",
    "OverallEngine",
    "OverallInputs",
    "OverallQualityFlag",
    "OverallValuationError",
    "OverallValuationResult",
    "QualityFlag",
    "RELATIVE_VERSION",
    "RESEARCH_DISCLAIMER",
    "RESIDUAL_INCOME_VERSION",
    "REVERSE_DCF_VERSION",
    "RelativeEngine",
    "RelativeInputs",
    "RelativeMultiple",
    "RelativeQualityFlag",
    "RelativeValuationResult",
    "ResearchLabel",
    "ResidualIncomeEngine",
    "ResidualIncomeInputs",
    "ResidualIncomeResult",
    "ResidualIncomeScenario",
    "ReverseDcfEngine",
    "ReverseDcfInputs",
    "ReverseDcfResult",
    "ReverseDcfScenario",
    "ReverseExplainedValue",
    "RiExplainedValue",
    "RiQualityFlag",
    "RoeForecastModel",
    "MosClassification",
    "MosThresholds",
    "ScenarioEngine",
    "SensitivityEngine",
    "StaticMultipleProvider",
    "VALUATION_CORE_VERSION",
    "ValidationEngine",
    "ValuationAssessment",
    "ValuationAssumptions",
    "ValuationConfidence",
    "ValuationEngine",
    "ValuationError",
    "ValuationEvidence",
    "ValuationMetadata",
    "ValuationMethod",
    "ValuationRange",
    "ValuationResult",
    "WeightingMode",
    "to_asset_v2_aggregate_payload",
    "to_asset_valuation_result",
    "to_consensus_v2_aggregate_payload",
    "to_consensus_valuation_result",
    "to_ddm_v2_aggregate_payload",
    "to_ddm_valuation_result",
    "to_epv_v2_aggregate_payload",
    "to_epv_valuation_result",
    "to_graham_v2_aggregate_payload",
    "to_graham_valuation_result",
    "to_overall_v2_aggregate_payload",
    "to_overall_valuation_result",
    "to_relative_v2_aggregate_payload",
    "to_relative_valuation_result",
    "to_v2_aggregate_payload",
    "validate_asset_based_inputs",
    "validate_consensus_inputs",
    "validate_ddm_inputs",
    "validate_epv_inputs",
    "validate_graham_inputs",
    "validate_overall_inputs",
    "validate_relative_inputs",
    "validate_residual_income_inputs",
    "validate_reverse_dcf_inputs",
    "verify_clean_surplus",
]

__version__ = "0.12.0"
