apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsp
resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - redis.yaml
  - postgres.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: dsp-ai-indicator
  dsp.platform/epic: "017"
