apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsp
spec:
  tls:
    - hosts:
        - app.example.com
        - api.example.com
      secretName: dsp-tls
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsp-web
                port:
                  number: 3000
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: dsp-api
                port:
                  number: 8000
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsp-api
                port:
                  number: 8000
