export {
  PRODUCT_EDITIONS,
  FEATURE_MATRIX_ROWS,
  SUPPORT_CONTACT,
  COMMERCIAL_PRICING_DISCLOSURE,
  SAMPLE_ANALYSIS_SYMBOL,
  COMMERCIAL_CHANNEL,
  type ProductEdition,
  type ProductEditionId,
} from "./editions";
