"""Build and render git recovery plans."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from tools.git_recovery.classifier import classify_files
from tools.git_recovery.models import RecoveryPlan
from tools.git_recovery.parser import parse_porcelain


def build_plan(
    porcelain_text: str,
    *,
    branch: str = "unknown",
    remote: str = "origin",
) -> RecoveryPlan:
    files = parse_porcelain(porcelain_text)
    groups = classify_files(files)
    ignored = []
    commit_groups = []
    for g in groups:
        if g.action == "IGNORE":
            ignored.extend(g.files)
        else:
            commit_groups.append(g)
    return RecoveryPlan(
        branch=branch,
        remote=remote,
        total_files=len(files),
        groups=commit_groups,
        ignored=ignored,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )


def render_plan_markdown(plan: RecoveryPlan) -> str:
    lines: list[str] = []
    lines.append("# Git Recovery Plan")
    lines.append("")
    lines.append("Generated by `tools/git_recovery` — analysis / guided recovery.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| Generated at (UTC) | `{plan.generated_at}` |")
    lines.append(f"| Branch | `{plan.branch}` |")
    lines.append(f"| Remote | `{plan.remote}` |")
    lines.append(f"| Total porcelain files | **{plan.total_files}** |")
    lines.append(f"| Commit groups | **{len(plan.commit_groups)}** |")
    lines.append(f"| Ignored (never commit) | **{len(plan.ignored)}** |")
    lines.append("")
    lines.append("### Safety rules")
    lines.append("")
    lines.append("- Never `git add -A`")
    lines.append("- Never commit everything in one shot")
    lines.append("- Never `git push --force`")
    lines.append("- Never rewrite history")
    lines.append("- Stage only files listed in the current group")
    lines.append("")
    lines.append("## Groups")
    lines.append("")

    for idx, group in enumerate(plan.commit_groups, start=1):
        lines.append(f"### GROUP {idx}: {group.title}")
        lines.append("")
        lines.append(f"- **Key:** `{group.key}`")
        lines.append(f"- **Purpose:** {group.purpose}")
        lines.append(f"- **Epic:** {group.epic}")
        lines.append(f"- **Package:** {group.package}")
        lines.append(f"- **Action:** {group.action}")
        lines.append(f"- **Estimated Risk:** `{group.risk.value}`")
        deps = ", ".join(f"`{d}`" for d in group.depends_on) if group.depends_on else "_none_"
        lines.append(f"- **Dependencies:** {deps}")
        lines.append(f"- **Suggested Commit Message:** `{group.suggested_message}`")
        lines.append(f"- **Files ({len(group.files)}):**")
        lines.append("")
        for item in group.files:
            rename = f" (from `{item.original_path}`)" if item.original_path else ""
            lines.append(f"  - `{item.status}` `{item.path}`{rename}")
        lines.append("")

    if plan.ignored:
        lines.append("## Ignored (never commit)")
        lines.append("")
        lines.append("These paths are classified as build outputs, caches, or secrets.")
        lines.append("")
        for item in plan.ignored:
            lines.append(f"- `{item.status}` `{item.path}`")
        lines.append("")

    lines.append("## Recommended order")
    lines.append("")
    for idx, group in enumerate(plan.commit_groups, start=1):
        lines.append(f"{idx}. `{group.key}` — {group.suggested_message}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_End of recovery plan._")
    lines.append("")
    return "\n".join(lines)


def write_plan(plan: RecoveryPlan, output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_plan_markdown(plan), encoding="utf-8")
    return output
