"""Default Configuration Registry values (RC1 M11).

Config overlays only — never execute valuation/AI/risk engines.
Engines continue to read frozen defaults unless wired to consume registry.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

MODULE_IDS = (
    "platform",
    "branding",
    "cms",
    "feature_flags",
    "ai",
    "research",
    "portfolio",
    "valuation",
    "risk",
    "workflow",
    "dashboard",
    "saas",
    "security",
    "market",
    "notifications",
    "exports",
    "regional",
    "connectors",
    "business_rules",
    "templates",
    "monitoring",
    "backup",
    "release",
    "users_orgs",
)

DEFAULT_REGISTRY: dict[str, dict[str, Any]] = {
    "platform": {
        "company_name": "DSP AI Indicator",
        "copyright": "© DSP AI Indicator",
        "default_locale": "en-IN",
        "support_email": None,
        "maintenance_mode": False,
    },
    "branding": {
        "logo_url": None,
        "favicon_url": None,
        "theme": "system",
        "font_family": None,
        "primary_color": "#0f766e",
        "icon_set": "default",
        "background_style": "subtle",
        "login_hero_url": None,
        "landing_hero_url": None,
        "footer_text": None,
        "watermark": None,
        "company_name": "DSP AI Indicator",
        "copyright": "© DSP AI Indicator",
    },
    "cms": {
        "pages": {
            "home": {"title": "Home", "body": "Data unavailable.", "published": False},
            "about": {"title": "About", "body": "Data unavailable.", "published": False},
            "contact": {"title": "Contact", "body": "Data unavailable.", "published": False},
            "faq": {"title": "FAQ", "body": "Data unavailable.", "published": False},
            "privacy": {"title": "Privacy", "body": "Data unavailable.", "published": False},
            "terms": {"title": "Terms", "body": "Data unavailable.", "published": False},
            "disclaimer": {
                "title": "Disclaimer",
                "body": "Research Mode — not investment advice.",
                "published": True,
            },
            "blog": {"title": "Blog", "body": "Data unavailable.", "published": False},
        }
    },
    "feature_flags": {
        "copilot": True,
        "portfolio": True,
        "workflow": True,
        "research": True,
        "exports": True,
        "pdf": True,
        "docx": True,
        "pptx": False,
        "news": True,
        "esg": True,
        "dashboards": True,
        "saas": True,
        "experimental": False,
        "research_workspace": True,
        "production_ops": True,
        "control_center": True,
    },
    "ai": {
        "default_provider": None,
        "models": {},
        "temperature": 0.2,
        "top_p": 0.9,
        "max_tokens": 2048,
        "response_length": "medium",
        "confidence_threshold": None,
        "token_limits": {"per_request": 4096, "per_day": None},
        "model_routing": {},
        "prompt_library": {},
        "system_prompts": {},
        "committee_enabled": True,
        "note": "Provider secrets stay in env / SecretsPort — never stored here in plaintext.",
    },
    "research": {
        "default_mode": "research",
        "require_authenticated_data": True,
        "sections_enabled": list(range(1, 11)),
    },
    "portfolio": {
        "max_holdings_default": 100,
        "intelligence_enabled": True,
        "demo_mode": False,
    },
    "valuation": {
        "methods": {
            "dcf": {"enabled": True, "defaults": {}},
            "reverse_dcf": {"enabled": True, "defaults": {}},
            "residual_income": {"enabled": True, "defaults": {}},
            "epv": {"enabled": True, "defaults": {}},
            "graham": {"enabled": True, "defaults": {}},
            "relative": {"enabled": True, "defaults": {}},
        },
        "margin_of_safety": {"default_pct": None, "note": "Unable to calculate. without engine inputs"},
        "wacc": {"default": None},
        "terminal_growth": {"default": None},
        "risk_free_rate": {"default": None},
        "inflation": {"default": None},
        "buffett_indicator_weights": {},
        "economic_moat_weights": {},
        "risk_score_weights": {},
        "consensus_model": {"enabled": True},
        "sector_defaults": {
            "banks": {},
            "nbfc": {},
            "insurance": {},
            "amc": {},
            "it": {},
            "fmcg": {},
            "utilities": {},
            "reit": {},
            "pharma": {},
            "manufacturing": {},
            "telecom": {},
            "logistics": {},
            "chemicals": {},
            "cement": {},
            "healthcare": {},
        },
        "note": "Overlays only — engines never recalculated here.",
    },
    "risk": {
        "categories": [],
        "thresholds": {},
        "stress_scenarios": [],
        "monte_carlo": {"enabled": False, "paths": None},
        "risk_weights": {},
        "alert_thresholds": {},
    },
    "workflow": {
        "default_template": "institutional_research_v1",
        "approval_required": True,
        "publishing_rules": {},
    },
    "dashboard": {
        "sidebar": [],
        "widgets": {},
        "role_dashboards": {},
        "landing_pages": {},
        "visibility": {},
        "widget_order": [],
    },
    "saas": {
        "default_plan": "starter",
        "trial_days": 14,
        "coupons_enabled": True,
        "seat_defaults": {},
        "storage_defaults": {},
        "usage_limits": {},
        "organization_defaults": {},
        "note": "Managed via /saas and saas_platform — registry mirrors policy overlays.",
    },
    "security": {
        "password_min_length": 12,
        "oauth_providers": [],
        "mfa_required": False,
        "session_timeout_minutes": 60,
        "rate_limits": {},
        "allowed_domains": [],
        "ip_whitelist": [],
        "cookie_policy": "strict",
        "security_headers": {"csp": None, "hsts": True},
    },
    "market": {
        "benchmarks": [],
        "tax": {},
        "inflation": None,
        "currencies": ["INR", "USD"],
        "holiday_calendar": None,
        "trading_hours": {},
        "exchange_mapping": {"NSE": "IN", "BSE": "IN"},
        "regional_defaults": {"country": "IN", "timezone": "Asia/Kolkata"},
    },
    "notifications": {
        "channels": {"email": True, "sms": False, "push": False},
        "announcements": [],
        "maintenance_banners": [],
        "offers": [],
        "scheduling": {},
        "priority_defaults": "normal",
    },
    "exports": {
        "pdf": True,
        "docx": True,
        "pptx": False,
        "branding": {},
        "templates": {},
    },
    "regional": {
        "timezone": "Asia/Kolkata",
        "date_format": "YYYY-MM-DD",
        "number_format": "en-IN",
        "currency": "INR",
        "language": "en",
    },
    "connectors": {
        "providers": {
            "yahoo": {"enabled": True, "priority": 10},
            "polygon": {"enabled": False, "priority": 20},
            "fmp": {"enabled": False, "priority": 30},
            "screener": {"enabled": False, "priority": 40},
            "nse": {"enabled": True, "priority": 5},
            "bse": {"enabled": True, "priority": 6},
        },
        "failover": True,
        "rate_limits": {},
        "api_keys_ref": "SecretsPort / env — never plaintext here",
        "note": "Priority overlays for Data Connector Framework — no duplicate connectors.",
    },
    "business_rules": {
        "rules": [],
        "note": "Configurable rules evaluated by orchestration consumers — no hardcoded alerts.",
    },
    "templates": {
        "email": {},
        "research": {},
        "portfolio": {},
        "invoice": {},
        "report": {},
        "export_branding": {},
    },
    "monitoring": {
        "reuse": ["/ops/dashboard", "/ops/metrics", "/admin/metrics", "/admin/health"],
        "note": "View-only aggregation — Production Operations owns probes.",
    },
    "backup": {
        "reuse": ["/ops/backup", "BackupPort"],
        "configuration_backup_enabled": True,
        "note": "Never fabricate snapshots.",
    },
    "release": {
        "environments": ["development", "testing", "staging", "production"],
        "release_notes": [],
        "deployment_history": [],
        "note": "Build info from /ops/version.",
    },
    "users_orgs": {
        "reuse": [
            "/admin/users",
            "/admin/roles",
            "/saas/organizations",
            "/enterprise/*",
        ],
        "note": "Identity stays in Enterprise Auth / IAM — no duplicate user store.",
    },
}


def default_module(module_id: str) -> dict[str, Any]:
    return deepcopy(DEFAULT_REGISTRY.get(module_id, {}))


def full_defaults() -> dict[str, dict[str, Any]]:
    return deepcopy(DEFAULT_REGISTRY)
