"""DSP AI Indicator platform façade.

Sprint 7.3 — public entry point with health checks, optional config
loaders, and application import-boundary contracts.

Import name is ``dsp_platform`` (not ``platform``) to avoid shadowing
Python's standard-library ``platform`` module.
"""

from __future__ import annotations

from comparison import (
    ComparisonDimensionResult,
    ComparisonError,
    ComparisonEvidenceSummary,
    ComparisonExplanation,
    ComparisonLimitation,
    ComparisonObservation,
    ComparisonReport,
    ComparisonRequest,
    ComparisonResult,
    ComparisonStatus,
    QualitativeComparisonEngine,
    compare_universe_result,
    comparison_result_public_dict,
)
from decision_intelligence import (
    AssuranceAssessment,
    AssuranceLevel,
    DecisionBrief,
    DecisionIntelligenceService,
    DecisionPack,
    DecisionPackEvidenceSummary,
    DecisionPackView,
    GuidanceStance,
    attach_evidence_bundle_ref,
    present_decision_pack,
)
from dsp_platform.boundaries import (
    ALLOWED_APPLICATION_PACKAGES,
    FORBIDDEN_APPLICATION_PACKAGES,
    PLATFORM_PACKAGES,
    assert_application_imports,
    assert_public_sibling_imports,
    scan_cross_package_deep_imports,
    scan_module_imports,
)
from dsp_platform.config import (
    CacheSettings,
    Environment,
    FeatureFlags,
    PlatformConfig,
    PlatformSecrets,
    ProviderSettings,
    TimeoutSettings,
)
from dsp_platform.exceptions import (
    PlatformConfigurationError,
    PlatformError,
    PlatformLifecycleError,
    ServiceRegistryError,
)
from dsp_platform.comparison_engine import build_default_comparison_engine
from dsp_platform.facade import DSPPlatform
from dsp_platform.composition import (
    COMPOSITION_PIPELINE_VERSION,
    EXECUTION_ORDER,
    CompanyRiskView,
    CompositionInputError,
    CompositionRequest,
    CompositionStageError,
    DependencyResolver,
    ExecutionContext,
    ExecutionMetadata,
    ExecutionTraceEntry,
    PipelineConfiguration,
    PipelineResult,
    PipelineStage,
    PlatformOrchestrator,
    RiskCategoryView,
    StageOutcome,
    StageStatus,
    build_composition_request,
    composition_capability_manifest,
    composition_package_versions,
    pipeline_result_public_dict,
    run_execution_pipeline,
)
from dsp_platform.configuration import (
    DEFAULT_CAPABILITIES,
    PlatformConfiguration,
)
from dsp_platform.lifecycle import PlatformLifecycle, PlatformStatus
from dsp_platform.platform import (
    PlatformBuilder,
    PlatformMetadata,
    PlatformResult,
)
from dsp_platform.service_registry import ServiceDescriptor, ServiceRegistry
from dsp_platform.health import (
    CheckStatus,
    HealthCheckResult,
    PlatformHealthReport,
    PlatformHealthService,
)
from dsp_platform.loaders import load_platform_config, load_secrets_from_environ
from portfolio import (
    ComparisonReportReference,
    CoverageSummary,
    DecisionPackReference,
    Portfolio,
    PortfolioAllocation,
    PortfolioAnalysisContext,
    PortfolioAnalysisResult,
    PortfolioAnalysisStatus,
    PortfolioAnalyzer,
    PortfolioAssembler,
    PortfolioAssemblyContext,
    PortfolioAssemblyResult,
    PortfolioAssemblyStatus,
    PortfolioChange,
    PortfolioChangeType,
    PortfolioCitationAssembler,
    PortfolioCitationContext,
    PortfolioCitationResult,
    PortfolioCitationStatus,
    PortfolioCitationSummary,
    PortfolioConstraint,
    PortfolioConstraintKind,
    PortfolioDescriptor,
    PortfolioError,
    PortfolioHolding,
    PortfolioHoldingInput,
    PortfolioIdentity,
    PortfolioMonitor,
    PortfolioMonitoringContext,
    PortfolioMonitoringResult,
    PortfolioMonitoringStatus,
    PortfolioMonitoringSummary,
    PortfolioObservation,
    PortfolioReport,
    PortfolioSnapshot,
    PortfolioSummary,
    PortfolioTimeline,
    PortfolioType,
)
from risk import (
    IntegratedRiskContext,
    MonitoringReference,
    PortfolioReference,
    RiskAnalysisContext,
    RiskAnalysisResult,
    RiskAnalysisStatus,
    RiskAnalyzer,
    RiskAssembler,
    RiskAssemblyContext,
    RiskAssemblyResult,
    RiskAssemblyStatus,
    RiskAssessment,
    RiskConstraint,
    RiskConstraintKind,
    RiskCoverage,
    RiskCoverageKind,
    RiskCoverageStatus,
    RiskDescriptor,
    RiskError,
    RiskIdentity,
    RiskIntegrationContext,
    RiskIntegrationResult,
    RiskIntegrationStatus,
    RiskIntegrator,
    RiskLevel,
    RiskObservation,
    RiskProfile,
    RiskReport,
    RiskReporter,
    RiskReportingContext,
    RiskReportingResult,
    RiskReportingStatus,
    RiskSummary,
)
from research import (
    ComparisonReference,
    DecisionReference,
    EvidenceReference,
    IntegratedRiskReference,
    ResearchAgenda,
    ResearchAssembler,
    ResearchAssemblyContext,
    ResearchAssemblyResult,
    ResearchAssemblyStatus,
    ResearchConflict,
    ResearchConflictSeverity,
    ResearchCoverage,
    ResearchCoverageStatus,
    ResearchError,
    ResearchGap,
    ResearchGapStatus,
    ResearchIdentity,
    ResearchInsight,
    ResearchObservation,
    ResearchPriority,
    ResearchPriorityLevel,
    ResearchProfile,
    ResearchReport,
    ResearchReporter,
    ResearchReportingContext,
    ResearchReportingResult,
    ResearchReportingStatus,
    ResearchSummary,
    ResearchSynthesisContext,
    ResearchSynthesisResult,
    ResearchSynthesisStatus,
    ResearchSynthesizer,
    RiskReference,
)
from research import (
    MonitoringReference as ResearchMonitoringReference,
)
from research import (
    PortfolioReference as ResearchPortfolioReference,
)
from quantitative_risk import (
    BenchmarkDataPort,
    BenchmarkReference as QuantitativeBenchmarkReference,
    DrawdownProfile,
    EngineContext,
    EngineResult,
    EngineStatus,
    HistoricalReturnsPort,
    HistoricalReturnsReference,
    MarketDataPort,
    MarketDataReference,
    MetricCollection,
    MetricStatus,
    MetricType,
    QuantitativeRiskEngine,
    QuantitativeRiskError,
    QuantitativeRiskIdentity,
    QuantitativeRiskProfile,
    QuantitativeRiskReport,
    QuantitativeRiskReporter,
    QuantitativeRiskSummary,
    ReportMetadata,
    ReportingContext,
    ReportingResult,
    ReportingStatus,
    ResearchReference as QuantitativeResearchReference,
    ReturnPoint,
    RiskConcentration,
    RiskCorrelation,
    RiskDistribution,
    RiskExposure,
    RiskMetric,
    RiskVolatility,
    ScenarioResult,
    StressScenario,
    StressScenarioType,
    WeightPoint,
)
from quantitative_risk import (
    MonitoringReference as QuantitativeRiskMonitoringReference,
)
from quantitative_risk import (
    PortfolioReference as QuantitativeRiskPortfolioReference,
)
from recommendation import (
    AssemblyContext,
    AssemblyResult,
    AssemblyStatus,
    CitationSection,
    ConfidenceLevel,
    ConflictSeverity,
    EngineContext,
    EngineResult,
    EngineStatus,
    RecommendationAssembler,
    RecommendationConflict,
    RecommendationEngine,
    RecommendationError,
    RecommendationIdentity,
    RecommendationMapper,
    RecommendationMappingError,
    RecommendationOption,
    RecommendationProfile,
    RecommendationRationale,
    RecommendationReport,
    RecommendationReporter,
    RecommendationScore,
    RecommendationSummary,
    RecommendationType,
    ReportMetadata,
    ReportingContext,
    ReportingResult,
    ReportingStatus,
    SignalPosture,
)
from recommendation import (
    ComparisonReference as RecommendationComparisonReference,
)
from recommendation import (
    DecisionReference as RecommendationDecisionReference,
)
from recommendation import (
    PortfolioReference as RecommendationPortfolioReference,
)
from recommendation import (
    QuantitativeRiskReference as RecommendationQuantitativeRiskReference,
)
from recommendation import (
    ResearchReference as RecommendationResearchReference,
)
from recommendation import (
    RiskReference as RecommendationRiskReference,
)
from workflow import (
    ALLOWED_STEP_TRANSITIONS,
    ALLOWED_WORKFLOW_TRANSITIONS,
    BackoffPolicy,
    ExecutionAudit,
    FailureClass,
    FailureDescriptor,
    RetryPolicy,
    StepExecutionResult,
    StepFacadeResult,
    WorkflowAssembler,
    WorkflowEngine,
    WorkflowError,
    WorkflowExecution,
    WorkflowIdentity,
    WorkflowMetadata,
    WorkflowProfile,
    WorkflowReport,
    WorkflowReporter,
    WorkflowState,
    WorkflowStep,
    WorkflowStepState,
    WorkflowSummary,
    WorkflowTransition,
    assert_legal_step_transition,
    assert_legal_workflow_transition,
    assert_unique_workflow_ids,
    require_decimal,
    validate_retry_policy_fields,
)
from workflow import (
    AnalysisReference as WorkflowAnalysisReference,
)
from workflow import (
    AssemblyContext as WorkflowAssemblyContext,
)
from workflow import (
    AssemblyResult as WorkflowAssemblyResult,
)
from workflow import (
    AssemblyStatus as WorkflowAssemblyStatus,
)
from workflow import (
    ComparisonReference as WorkflowComparisonReference,
)
from workflow import (
    DecisionReference as WorkflowDecisionReference,
)
from workflow import (
    EngineContext as WorkflowEngineContext,
)
from workflow import (
    EngineResult as WorkflowEngineResult,
)
from workflow import (
    EngineStatus as WorkflowEngineStatus,
)
from workflow import (
    ExecutionResult as WorkflowExecutionResult,
)
from workflow import (
    ExecutionSection as WorkflowExecutionSection,
)
from workflow import (
    IndustryEvidenceReference as WorkflowIndustryEvidenceReference,
)
from workflow import (
    PortfolioReference as WorkflowPortfolioReference,
)
from workflow import (
    QuantitativeRiskReference as WorkflowQuantitativeRiskReference,
)
from workflow import (
    RecommendationReference as WorkflowRecommendationReference,
)
from workflow import (
    ReportMetadata as WorkflowReportMetadata,
)
from workflow import (
    ReportingContext as WorkflowReportingContext,
)
from workflow import (
    ReportingResult as WorkflowReportingResult,
)
from workflow import (
    ReportingStatus as WorkflowReportingStatus,
)
from workflow import (
    ResearchReference as WorkflowResearchReference,
)
from workflow import (
    RiskReference as WorkflowRiskReference,
)
from knowledge_graph import (
    EvidenceLink,
    EvidenceLinkCategory,
    GraphEdge,
    GraphIdentity,
    GraphMetadata,
    GraphNode,
    GraphProfile,
    GraphRelationship,
    GraphSummary,
    KnowledgeGraphAssembler,
    KnowledgeGraphEngine,
    KnowledgeGraphError,
    KnowledgeGraphReport,
    KnowledgeGraphReporter,
    Lineage,
    LineageCategory,
    NodeCategory,
    RelationshipCategory,
    ReportMetadata as KnowledgeGraphReportMetadata,
    ReportingStatus as KnowledgeGraphReportingStatus,
    assert_evidence_link_category,
    assert_lineage_category,
    assert_node_category,
    assert_relationship_category,
    assert_unique_graph_ids,
)
from knowledge_graph import (
    AnalysisReference as KnowledgeGraphAnalysisReference,
)
from knowledge_graph import (
    AssemblyContext as KnowledgeGraphAssemblyContext,
)
from knowledge_graph import (
    AssemblyResult as KnowledgeGraphAssemblyResult,
)
from knowledge_graph import (
    AssemblyStatus as KnowledgeGraphAssemblyStatus,
)
from knowledge_graph import (
    CategoryCount as KnowledgeGraphCategoryCount,
)
from knowledge_graph import (
    CollectionStatistics as KnowledgeGraphCollectionStatistics,
)
from knowledge_graph import (
    ComparisonReference as KnowledgeGraphComparisonReference,
)
from knowledge_graph import (
    DecisionReference as KnowledgeGraphDecisionReference,
)
from knowledge_graph import (
    EngineContext as KnowledgeGraphEngineContext,
)
from knowledge_graph import (
    EngineResult as KnowledgeGraphEngineResult,
)
from knowledge_graph import (
    EngineStatus as KnowledgeGraphEngineStatus,
)
from knowledge_graph import (
    IndustryEvidenceReference as KnowledgeGraphIndustryEvidenceReference,
)
from knowledge_graph import (
    PortfolioReference as KnowledgeGraphPortfolioReference,
)
from knowledge_graph import (
    QuantitativeRiskReference as KnowledgeGraphQuantitativeRiskReference,
)
from knowledge_graph import (
    RecommendationReference as KnowledgeGraphRecommendationReference,
)
from knowledge_graph import (
    ReportingContext as KnowledgeGraphReportingContext,
)
from knowledge_graph import (
    ReportingResult as KnowledgeGraphReportingResult,
)
from knowledge_graph import (
    ResearchReference as KnowledgeGraphResearchReference,
)
from knowledge_graph import (
    RiskReference as KnowledgeGraphRiskReference,
)
from knowledge_graph import (
    ValidationStatusView as KnowledgeGraphValidationStatusView,
)
from knowledge_graph import (
    WorkflowReference as KnowledgeGraphWorkflowReference,
)
from copilot import (
    CategoryCount,
    CollectionStatistics,
    ContextBundle,
    ContextBuilder,
    ConversationContext,
    ConversationEngine,
    ConversationEngineContext,
    ConversationResult,
    ConversationRole,
    ConversationSession,
    ConversationState,
    ConversationStatus,
    ConversationTurn,
    CopilotError,
    CopilotIdentity,
    CopilotMetadata,
    CopilotProfile,
    CopilotReporter,
    CopilotResponse,
    CopilotSummary,
    ConfidenceLevel,
    EvidenceValidator,
    Explanation,
    ExplanationDraft,
    ExplanationEngine,
    ExplanationInput,
    ExplanationResult,
    ExplanationStatus,
    ExplanationType,
    LanguageModelPort,
    LanguageModelRequest,
    LanguageModelResult,
    LanguageModelStatus,
    ReportFormatter,
    ReportingContext,
    ReportingResult,
    ResponseFormatter,
    ResponseMetadata,
    ResponseMetadataBuilder,
    ResponseStatus,
    UserIntent,
    UserIntentType,
    ValidationStatusView,
    assert_conversation_role,
    assert_conversation_state,
    assert_conversation_status,
    assert_explanation_type,
    assert_language_model_status,
    assert_legal_conversation_transition,
    assert_response_status,
    assert_unique_copilot_ids,
    assert_unique_session_ids,
    assert_unique_turn_ids,
    assert_user_intent_type,
)
from copilot import (
    AnalysisReference as CopilotAnalysisReference,
)
from copilot import (
    ComparisonReference as CopilotComparisonReference,
)
from copilot import (
    DecisionReference as CopilotDecisionReference,
)
from copilot import (
    IndustryEvidenceReference as CopilotIndustryEvidenceReference,
)
from copilot import (
    KnowledgeGraphReference as CopilotKnowledgeGraphReference,
)
from copilot import (
    PortfolioReference as CopilotPortfolioReference,
)
from copilot import (
    QuantitativeRiskReference as CopilotQuantitativeRiskReference,
)
from copilot import (
    RecommendationReference as CopilotRecommendationReference,
)
from copilot import (
    ResearchReference as CopilotResearchReference,
)
from copilot import (
    RiskReference as CopilotRiskReference,
)
from copilot import (
    WorkflowReference as CopilotWorkflowReference,
)
from industry import (
    ApplicabilityGroup,
    ApplicabilityLevel,
    AssembledMethodology,
    CharacteristicDefaults,
    CharacteristicLifecycle,
    ClassificationMappingRegistry,
    ClassificationReference,
    ComparisonDimension,
    ComparisonDimensionHint,
    EligibilityOptions,
    EvidenceApplicabilityRule,
    EvidenceAvailability,
    EvidenceBundle,
    EvidenceBundleAssembler,
    EvidenceBundleAssemblyContext,
    EvidenceBundleEntry,
    EvidenceBundleMetadata,
    EvidenceBundleReference,
    EvidenceBundleStatus,
    EvidenceBundleSummary,
    EvidenceCategory,
    EvidenceInterpretation,
    EvidenceInterpretationContext,
    EvidenceInterpreter,
    EvidenceLifecycle,
    EvidenceObservation,
    EvidenceObservationCategory,
    EvidenceObservationConfidence,
    EvidenceObservationSeverity,
    EvidenceProvider,
    EvidenceProviderCapability,
    EvidenceProviderRef,
    EvidenceProviderResult,
    EvidenceResolutionContext,
    EvidenceSnapshotRef,
    EvidenceVersion,
    GroupEligibilityResult,
    GroupEligibilityStatus,
    IdentityLifecycle,
    IndustryError,
    IndustryEvidenceApplicability,
    IndustryEvidenceApplicabilityRegistry,
    IndustryEvidenceDefinition,
    IndustryEvidenceInterpreter,
    IndustryEvidenceInterpreterRegistry,
    IndustryEvidenceProvider,
    IndustryEvidenceProviderRegistry,
    IndustryEvidenceRegistry,
    IndustryIdentity,
    IndustryMapping,
    IndustryMethodology,
    IndustryMethodologyRegistry,
    IndustryMetricDefinition,
    IndustryMetricRegistry,
    IndustryProfile,
    IndustryProfileRegistry,
    IndustryTaxonomy,
    InstrumentIndustryAssignment,
    InstrumentIndustryRegistry,
    InstrumentMethodologyResolution,
    InvestmentCharacteristics,
    InvestmentCharacteristicsRegistry,
    MappingStatus,
    MergeSource,
    MetricApplicability,
    MetricAvailability,
    MetricUnit,
    MethodologyLifecycle,
    MissingEvidencePolicy,
    PeerEligibilityEvaluator,
    PeerEligibilityPolicy,
    PeerEligibilityPolicyRef,
    PeerEligibilityPolicyRegistry,
    PeerEligibilityReason,
    PeerEligibilityResult,
    PeerEligibilityStatus,
    PlaceholderEvidenceInterpreter,
    PlaceholderEvidenceProvider,
    RequiredEvidenceSet,
    TaxonomySource,
    ValuationPhilosophyHint,
    ValuationProfile,
    assemble_methodology,
    build_example_archetypes,
    build_example_evidence_interpreters,
    build_example_evidence_providers,
    build_example_methodologies,
    register_example_archetypes,
    register_example_evidence_interpreters,
    register_example_evidence_providers,
    register_example_methodologies,
    resolve_methodology_for_instrument,
    seed_example_evidence_applicability_context,
    seed_example_evidence_bundle_assembler,
    seed_example_evidence_bundle_context,
    seed_example_evidence_interpreter_context,
    seed_example_evidence_provider_context,
    seed_example_evidence_registries,
)
from orchestration import AnalysisRequest
from universe import (
    BatchFailurePolicy,
    BatchStatus,
    ComparableDecisionSummary,
    InstrumentAnalysisFailure,
    InstrumentAnalysisOutcome,
    InstrumentOutcomeStatus,
    InvestmentUniverse,
    MultiStockAnalysisRequest,
    MultiStockAnalysisService,
    MultiStockDecisionResult,
    UniverseEntry,
    UniverseError,
    filter_entries,
    group_entries,
    summarize_decision_pack,
)

__all__ = [
    "ALLOWED_APPLICATION_PACKAGES",
    "AnalysisRequest",
    "ApplicabilityGroup",
    "ApplicabilityLevel",
    "AssembledMethodology",
    "AssuranceAssessment",
    "AssuranceLevel",
    "BatchFailurePolicy",
    "BatchStatus",
    "CacheSettings",
    "CheckStatus",
    "CharacteristicDefaults",
    "CharacteristicLifecycle",
    "ClassificationMappingRegistry",
    "ClassificationReference",
    "ComparableDecisionSummary",
    "ComparisonDimension",
    "ComparisonDimensionHint",
    "ComparisonDimensionResult",
    "ComparisonError",
    "ComparisonEvidenceSummary",
    "ComparisonExplanation",
    "ComparisonLimitation",
    "ComparisonObservation",
    "ComparisonReport",
    "ComparisonRequest",
    "ComparisonResult",
    "ComparisonStatus",
    "ComparisonReportReference",
    "COMPOSITION_PIPELINE_VERSION",
    "CompanyRiskView",
    "CompositionInputError",
    "CompositionRequest",
    "CompositionStageError",
    "DSPPlatform",
    "DecisionBrief",
    "DecisionIntelligenceService",
    "DecisionPack",
    "DecisionPackEvidenceSummary",
    "DecisionPackReference",
    "DecisionPackView",
    "EXECUTION_ORDER",
    "EligibilityOptions",
    "Environment",
    "ExecutionContext",
    "ExecutionMetadata",
    "ExecutionTraceEntry",
    "EvidenceApplicabilityRule",
    "EvidenceAvailability",
    "EvidenceBundle",
    "EvidenceBundleAssembler",
    "EvidenceBundleAssemblyContext",
    "EvidenceBundleEntry",
    "EvidenceBundleMetadata",
    "EvidenceBundleReference",
    "EvidenceBundleStatus",
    "EvidenceBundleSummary",
    "EvidenceCategory",
    "EvidenceInterpretation",
    "EvidenceInterpretationContext",
    "EvidenceInterpreter",
    "EvidenceLifecycle",
    "EvidenceObservation",
    "EvidenceObservationCategory",
    "EvidenceObservationConfidence",
    "EvidenceObservationSeverity",
    "EvidenceProvider",
    "EvidenceProviderCapability",
    "EvidenceProviderRef",
    "EvidenceProviderResult",
    "EvidenceResolutionContext",
    "EvidenceSnapshotRef",
    "EvidenceVersion",
    "FORBIDDEN_APPLICATION_PACKAGES",
    "FeatureFlags",
    "GroupEligibilityResult",
    "GroupEligibilityStatus",
    "GuidanceStance",
    "HealthCheckResult",
    "IdentityLifecycle",
    "IndustryError",
    "IndustryEvidenceApplicability",
    "IndustryEvidenceApplicabilityRegistry",
    "IndustryEvidenceDefinition",
    "IndustryEvidenceInterpreter",
    "IndustryEvidenceInterpreterRegistry",
    "IndustryEvidenceProvider",
    "IndustryEvidenceProviderRegistry",
    "IndustryEvidenceRegistry",
    "IndustryIdentity",
    "IndustryMapping",
    "IndustryMethodology",
    "IndustryMethodologyRegistry",
    "IndustryMetricDefinition",
    "IndustryMetricRegistry",
    "IndustryProfile",
    "IndustryProfileRegistry",
    "IndustryTaxonomy",
    "InstrumentAnalysisFailure",
    "InstrumentAnalysisOutcome",
    "InstrumentIndustryAssignment",
    "InstrumentIndustryRegistry",
    "InstrumentMethodologyResolution",
    "InstrumentOutcomeStatus",
    "InvestmentCharacteristics",
    "InvestmentCharacteristicsRegistry",
    "InvestmentUniverse",
    "MappingStatus",
    "MergeSource",
    "MetricApplicability",
    "MetricAvailability",
    "MetricUnit",
    "MethodologyLifecycle",
    "MissingEvidencePolicy",
    "MultiStockAnalysisRequest",
    "MultiStockAnalysisService",
    "MultiStockDecisionResult",
    "PLATFORM_PACKAGES",
    "PeerEligibilityEvaluator",
    "PeerEligibilityPolicy",
    "PeerEligibilityPolicyRef",
    "PeerEligibilityPolicyRegistry",
    "PeerEligibilityReason",
    "PeerEligibilityResult",
    "PeerEligibilityStatus",
    "PipelineConfiguration",
    "PipelineResult",
    "PipelineStage",
    "PlaceholderEvidenceInterpreter",
    "PlaceholderEvidenceProvider",
    "PlatformBuilder",
    "PlatformConfig",
    "PlatformConfiguration",
    "PlatformConfigurationError",
    "PlatformError",
    "PlatformHealthReport",
    "PlatformHealthService",
    "PlatformLifecycle",
    "PlatformLifecycleError",
    "PlatformMetadata",
    "PlatformOrchestrator",
    "PlatformResult",
    "build_composition_request",
    "build_default_comparison_engine",
    "composition_capability_manifest",
    "composition_package_versions",
    "pipeline_result_public_dict",
    "PlatformSecrets",
    "PlatformStatus",
    "RiskCategoryView",
    "DEFAULT_CAPABILITIES",
    "DependencyResolver",
    "ServiceDescriptor",
    "ServiceRegistry",
    "ServiceRegistryError",
    "StageOutcome",
    "StageStatus",
    "CoverageSummary",
    "Portfolio",
    "PortfolioAllocation",
    "PortfolioAnalysisContext",
    "PortfolioAnalysisResult",
    "PortfolioAnalysisStatus",
    "PortfolioAnalyzer",
    "PortfolioAssembler",
    "PortfolioAssemblyContext",
    "PortfolioAssemblyResult",
    "PortfolioAssemblyStatus",
    "PortfolioChange",
    "PortfolioChangeType",
    "PortfolioCitationAssembler",
    "PortfolioCitationContext",
    "PortfolioCitationResult",
    "PortfolioCitationStatus",
    "PortfolioCitationSummary",
    "PortfolioConstraint",
    "PortfolioConstraintKind",
    "PortfolioDescriptor",
    "PortfolioError",
    "PortfolioHolding",
    "PortfolioHoldingInput",
    "PortfolioIdentity",
    "PortfolioMonitor",
    "PortfolioMonitoringContext",
    "PortfolioMonitoringResult",
    "PortfolioMonitoringStatus",
    "PortfolioMonitoringSummary",
    "PortfolioObservation",
    "PortfolioReport",
    "PortfolioSnapshot",
    "PortfolioSummary",
    "PortfolioTimeline",
    "PortfolioType",
    "MonitoringReference",
    "PortfolioReference",
    "IntegratedRiskContext",
    "RiskAnalysisContext",
    "RiskAnalysisResult",
    "RiskAnalysisStatus",
    "RiskAnalyzer",
    "RiskAssembler",
    "RiskAssemblyContext",
    "RiskAssemblyResult",
    "RiskAssemblyStatus",
    "RiskAssessment",
    "RiskConstraint",
    "RiskConstraintKind",
    "RiskCoverage",
    "RiskCoverageKind",
    "RiskCoverageStatus",
    "RiskDescriptor",
    "RiskError",
    "RiskIdentity",
    "RiskIntegrationContext",
    "RiskIntegrationResult",
    "RiskIntegrationStatus",
    "RiskIntegrator",
    "RiskLevel",
    "RiskObservation",
    "RiskProfile",
    "RiskReport",
    "RiskReporter",
    "RiskReportingContext",
    "RiskReportingResult",
    "RiskReportingStatus",
    "RiskSummary",
    "ComparisonReference",
    "DecisionReference",
    "EvidenceReference",
    "IntegratedRiskReference",
    "ResearchAgenda",
    "ResearchAssembler",
    "ResearchAssemblyContext",
    "ResearchAssemblyResult",
    "ResearchAssemblyStatus",
    "ResearchConflict",
    "ResearchConflictSeverity",
    "ResearchCoverage",
    "ResearchCoverageStatus",
    "ResearchError",
    "ResearchGap",
    "ResearchGapStatus",
    "ResearchIdentity",
    "ResearchInsight",
    "ResearchMonitoringReference",
    "ResearchObservation",
    "ResearchPortfolioReference",
    "ResearchPriority",
    "ResearchPriorityLevel",
    "ResearchProfile",
    "ResearchReport",
    "ResearchReporter",
    "ResearchReportingContext",
    "ResearchReportingResult",
    "ResearchReportingStatus",
    "ResearchSummary",
    "ResearchSynthesisContext",
    "ResearchSynthesisResult",
    "ResearchSynthesisStatus",
    "ResearchSynthesizer",
    "RiskReference",
    "DrawdownProfile",
    "EngineContext",
    "EngineResult",
    "EngineStatus",
    "HistoricalReturnsPort",
    "HistoricalReturnsReference",
    "MarketDataPort",
    "MarketDataReference",
    "MetricCollection",
    "MetricStatus",
    "MetricType",
    "QuantitativeBenchmarkReference",
    "QuantitativeResearchReference",
    "QuantitativeRiskEngine",
    "QuantitativeRiskError",
    "QuantitativeRiskIdentity",
    "QuantitativeRiskMonitoringReference",
    "QuantitativeRiskPortfolioReference",
    "QuantitativeRiskProfile",
    "QuantitativeRiskReport",
    "QuantitativeRiskReporter",
    "QuantitativeRiskSummary",
    "ReportMetadata",
    "ReportingContext",
    "ReportingResult",
    "ReportingStatus",
    "ReturnPoint",
    "RiskConcentration",
    "RiskCorrelation",
    "RiskDistribution",
    "RiskExposure",
    "RiskMetric",
    "RiskVolatility",
    "ScenarioResult",
    "StressScenario",
    "StressScenarioType",
    "WeightPoint",
    "BenchmarkDataPort",
    "AssemblyContext",
    "AssemblyResult",
    "AssemblyStatus",
    "CitationSection",
    "ConfidenceLevel",
    "ConflictSeverity",
    "EngineContext",
    "EngineResult",
    "EngineStatus",
    "RecommendationAssembler",
    "RecommendationComparisonReference",
    "RecommendationConflict",
    "RecommendationDecisionReference",
    "RecommendationEngine",
    "RecommendationError",
    "RecommendationIdentity",
    "RecommendationMapper",
    "RecommendationMappingError",
    "RecommendationOption",
    "RecommendationPortfolioReference",
    "RecommendationProfile",
    "RecommendationQuantitativeRiskReference",
    "RecommendationRationale",
    "RecommendationReport",
    "RecommendationReporter",
    "RecommendationResearchReference",
    "RecommendationRiskReference",
    "RecommendationScore",
    "RecommendationSummary",
    "RecommendationType",
    "ReportMetadata",
    "ReportingContext",
    "ReportingResult",
    "ReportingStatus",
    "SignalPosture",
    "ALLOWED_STEP_TRANSITIONS",
    "ALLOWED_WORKFLOW_TRANSITIONS",
    "BackoffPolicy",
    "ExecutionAudit",
    "FailureClass",
    "FailureDescriptor",
    "RetryPolicy",
    "StepExecutionResult",
    "StepFacadeResult",
    "WorkflowAnalysisReference",
    "WorkflowAssembler",
    "WorkflowAssemblyContext",
    "WorkflowAssemblyResult",
    "WorkflowAssemblyStatus",
    "WorkflowComparisonReference",
    "WorkflowDecisionReference",
    "WorkflowEngine",
    "WorkflowEngineContext",
    "WorkflowEngineResult",
    "WorkflowEngineStatus",
    "WorkflowExecutionResult",
    "WorkflowExecutionSection",
    "WorkflowError",
    "WorkflowExecution",
    "WorkflowIdentity",
    "WorkflowIndustryEvidenceReference",
    "WorkflowMetadata",
    "WorkflowPortfolioReference",
    "WorkflowProfile",
    "WorkflowQuantitativeRiskReference",
    "WorkflowRecommendationReference",
    "WorkflowReport",
    "WorkflowReportMetadata",
    "WorkflowReporter",
    "WorkflowReportingContext",
    "WorkflowReportingResult",
    "WorkflowReportingStatus",
    "WorkflowResearchReference",
    "WorkflowRiskReference",
    "WorkflowState",
    "WorkflowStep",
    "WorkflowStepState",
    "WorkflowSummary",
    "WorkflowTransition",
    "assert_legal_step_transition",
    "assert_legal_workflow_transition",
    "assert_unique_workflow_ids",
    "require_decimal",
    "validate_retry_policy_fields",
    "EvidenceLink",
    "EvidenceLinkCategory",
    "GraphEdge",
    "GraphIdentity",
    "GraphMetadata",
    "GraphNode",
    "GraphProfile",
    "GraphRelationship",
    "GraphSummary",
    "KnowledgeGraphAnalysisReference",
    "KnowledgeGraphAssembler",
    "KnowledgeGraphAssemblyContext",
    "KnowledgeGraphAssemblyResult",
    "KnowledgeGraphAssemblyStatus",
    "KnowledgeGraphCategoryCount",
    "KnowledgeGraphCollectionStatistics",
    "KnowledgeGraphComparisonReference",
    "KnowledgeGraphDecisionReference",
    "KnowledgeGraphEngine",
    "KnowledgeGraphEngineContext",
    "KnowledgeGraphEngineResult",
    "KnowledgeGraphEngineStatus",
    "KnowledgeGraphError",
    "KnowledgeGraphIndustryEvidenceReference",
    "KnowledgeGraphPortfolioReference",
    "KnowledgeGraphQuantitativeRiskReference",
    "KnowledgeGraphRecommendationReference",
    "KnowledgeGraphReport",
    "KnowledgeGraphReportMetadata",
    "KnowledgeGraphReporter",
    "KnowledgeGraphReportingContext",
    "KnowledgeGraphReportingResult",
    "KnowledgeGraphReportingStatus",
    "KnowledgeGraphResearchReference",
    "KnowledgeGraphRiskReference",
    "KnowledgeGraphValidationStatusView",
    "KnowledgeGraphWorkflowReference",
    "Lineage",
    "LineageCategory",
    "NodeCategory",
    "RelationshipCategory",
    "assert_evidence_link_category",
    "assert_lineage_category",
    "assert_node_category",
    "assert_relationship_category",
    "assert_unique_graph_ids",
    "CategoryCount",
    "CollectionStatistics",
    "ConfidenceLevel",
    "ContextBundle",
    "ContextBuilder",
    "ConversationContext",
    "ConversationEngine",
    "ConversationEngineContext",
    "ConversationResult",
    "ConversationRole",
    "ConversationSession",
    "ConversationState",
    "ConversationStatus",
    "ConversationTurn",
    "CopilotAnalysisReference",
    "CopilotComparisonReference",
    "CopilotDecisionReference",
    "CopilotError",
    "CopilotIdentity",
    "CopilotIndustryEvidenceReference",
    "CopilotKnowledgeGraphReference",
    "CopilotMetadata",
    "CopilotPortfolioReference",
    "CopilotProfile",
    "CopilotQuantitativeRiskReference",
    "CopilotRecommendationReference",
    "CopilotReporter",
    "CopilotResearchReference",
    "CopilotResponse",
    "CopilotRiskReference",
    "CopilotSummary",
    "CopilotWorkflowReference",
    "EvidenceValidator",
    "Explanation",
    "ExplanationDraft",
    "ExplanationEngine",
    "ExplanationInput",
    "ExplanationResult",
    "ExplanationStatus",
    "ExplanationType",
    "LanguageModelPort",
    "LanguageModelRequest",
    "LanguageModelResult",
    "LanguageModelStatus",
    "ReportFormatter",
    "ReportingContext",
    "ReportingResult",
    "ResponseFormatter",
    "ResponseMetadata",
    "ResponseMetadataBuilder",
    "ResponseStatus",
    "UserIntent",
    "UserIntentType",
    "ValidationStatusView",
    "assert_conversation_role",
    "assert_conversation_state",
    "assert_conversation_status",
    "assert_explanation_type",
    "assert_language_model_status",
    "assert_legal_conversation_transition",
    "assert_response_status",
    "assert_unique_copilot_ids",
    "assert_unique_session_ids",
    "assert_unique_turn_ids",
    "assert_user_intent_type",
    "ProviderSettings",
    "QualitativeComparisonEngine",
    "RequiredEvidenceSet",
    "TaxonomySource",
    "TimeoutSettings",
    "UniverseEntry",
    "UniverseError",
    "ValuationPhilosophyHint",
    "ValuationProfile",
    "assemble_methodology",
    "assert_application_imports",
    "assert_public_sibling_imports",
    "attach_evidence_bundle_ref",
    "build_example_archetypes",
    "build_example_evidence_interpreters",
    "build_example_evidence_providers",
    "build_example_methodologies",
    "compare_universe_result",
    "comparison_result_public_dict",
    "filter_entries",
    "group_entries",
    "load_platform_config",
    "load_secrets_from_environ",
    "present_decision_pack",
    "register_example_archetypes",
    "register_example_evidence_interpreters",
    "register_example_evidence_providers",
    "register_example_methodologies",
    "resolve_methodology_for_instrument",
    "run_execution_pipeline",
    "scan_cross_package_deep_imports",
    "scan_module_imports",
    "seed_example_evidence_applicability_context",
    "seed_example_evidence_bundle_assembler",
    "seed_example_evidence_bundle_context",
    "seed_example_evidence_interpreter_context",
    "seed_example_evidence_provider_context",
    "seed_example_evidence_registries",
    "summarize_decision_pack",
]

__version__ = "2.0.0"
