"""Public DSP research report contract (unwired — schema only)."""

from __future__ import annotations

from dsp_platform.research_report.builder import build_public_research_report
from dsp_platform.research_report.models import (
    BUFFETT_METHODOLOGY,
    CANONICAL_VALUATION_AUTHORITY,
    FUTURE_VALIDATION_CHECKS,
    PRIVATE_REPORT_FIELD_NAMES,
    PUBLIC_RESEARCH_REPORT_SCHEMA_VERSION,
    PUBLIC_TOP_LEVEL_KEYS,
    SCORE_10_STATUS,
    AiNarrative,
    BuffettAnalysisPublic,
    DspValue,
    EntryExitPublic,
    EvidenceRefPublic,
    ExpectedReturnsPublic,
    FactorScorecardRow,
    FinancialsPublic,
    IdentityPublic,
    IndustryPublic,
    PublicMetric,
    PublicResearchReport,
    PublicResearchReportError,
    QualityFactorPublic,
    RecommendationPublic,
    ReportStatus,
    RiskCategoryPublic,
    RiskPublic,
    ScenariosPublic,
    UnavailableBlock,
    ValuationMethodPublic,
    ValuationPublic,
    ValuationRangePublic,
    assert_public_report_privacy,
    empty_ai_narrative,
)

__all__ = [
    "BUFFETT_METHODOLOGY",
    "CANONICAL_VALUATION_AUTHORITY",
    "FUTURE_VALIDATION_CHECKS",
    "PRIVATE_REPORT_FIELD_NAMES",
    "PUBLIC_RESEARCH_REPORT_SCHEMA_VERSION",
    "PUBLIC_TOP_LEVEL_KEYS",
    "SCORE_10_STATUS",
    "AiNarrative",
    "BuffettAnalysisPublic",
    "DspValue",
    "EntryExitPublic",
    "EvidenceRefPublic",
    "ExpectedReturnsPublic",
    "FactorScorecardRow",
    "FinancialsPublic",
    "IdentityPublic",
    "IndustryPublic",
    "PublicMetric",
    "PublicResearchReport",
    "PublicResearchReportError",
    "QualityFactorPublic",
    "RecommendationPublic",
    "ReportStatus",
    "RiskCategoryPublic",
    "RiskPublic",
    "ScenariosPublic",
    "UnavailableBlock",
    "ValuationMethodPublic",
    "ValuationPublic",
    "ValuationRangePublic",
    "assert_public_report_privacy",
    "build_public_research_report",
    "empty_ai_narrative",
]
