apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dsp.fullname" . }}-config
  labels:
    {{- include "dsp.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  DSP_REDIS_URL: {{ printf "redis://%s-redis:6379/0" (include "dsp.fullname" .) | quote }}
