import type {
  ConversationContextState,
  CopilotConversation,
  CopilotIntent,
  CopilotMessage,
  CopilotSourceRef,
  ResearchCitationId,
} from "./types";

export function createMessage(
  role: CopilotMessage["role"],
  content: string,
  citations?: ResearchCitationId[],
  extras?: { sources?: CopilotSourceRef[]; markdown?: boolean },
): CopilotMessage {
  return {
    id: `msg-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    role,
    content,
    createdAt: new Date().toISOString(),
    citations,
    sources: extras?.sources,
    markdown: extras?.markdown,
  };
}

export function emptyConversationContext(): ConversationContextState {
  return { lastIntent: null, lastTicker: null };
}

export function createConversation(title = "New conversation"): CopilotConversation {
  const now = new Date().toISOString();
  return {
    id: `conv-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    title,
    createdAt: now,
    updatedAt: now,
    context: emptyConversationContext(),
    messages: [
      createMessage(
        "assistant",
        "Ask a suggested question to explain existing research. Copilot 2.0 orchestrates Company Workspace, Valuation, Committee, Risk, Portfolio Intelligence, Comparison, and Documents — it never invents numbers.",
      ),
    ],
  };
}

export function appendExchange(
  conversation: CopilotConversation,
  userText: string,
  assistantText: string,
  options?: {
    citations?: ResearchCitationId[];
    intent?: CopilotIntent | null;
    ticker?: string | null;
    sources?: CopilotSourceRef[];
    markdown?: boolean;
    serverConversationId?: string | null;
  },
): CopilotConversation {
  const user = createMessage("user", userText);
  const assistant = createMessage("assistant", assistantText, options?.citations, {
    sources: options?.sources,
    markdown: options?.markdown,
  });
  return {
    ...conversation,
    id: options?.serverConversationId || conversation.id,
    title:
      conversation.messages.filter((m) => m.role === "user").length === 0
        ? userText.slice(0, 48)
        : conversation.title,
    updatedAt: new Date().toISOString(),
    context: {
      lastIntent: options?.intent ?? conversation.context.lastIntent,
      lastTicker: options?.ticker ?? conversation.context.lastTicker,
    },
    messages: [...conversation.messages, user, assistant],
  };
}

/** Export conversation as Markdown for download (presentation only). */
export function conversationToMarkdown(conversation: CopilotConversation): string {
  const lines = [
    `# ${conversation.title}`,
    "",
    `Updated: ${conversation.updatedAt}`,
    "",
  ];
  for (const message of conversation.messages) {
    const who = message.role === "user" ? "You" : "Copilot";
    lines.push(`## ${who}`, "", message.content, "");
    if (message.sources?.length) {
      lines.push("Sources:");
      for (const source of message.sources) {
        lines.push(`- ${source.engine ?? "engine"}${source.detail ? ` · ${source.detail}` : ""}`);
      }
      lines.push("");
    }
  }
  lines.push("_Generated by DSP AI Research Copilot 2.0 — orchestration only; no invented numbers._");
  return lines.join("\n");
}
