/**
 * Demo-only advisor fixtures — no persistence, no PII, no engine coupling.
 */

import type {
  Advisor,
  ClientNote,
  ClientRelationship,
  ClientSummary,
  Meeting,
  ModelPortfolio,
  ResearchCollection,
  ResearchHistoryEvent,
  Task,
} from "./advisorTypes";

export const DEMO_TRUST_BANNER =
  "Advisor demo layer only — does not alter research conclusions, evidence, confidence, methodology, or decision traces.";

export const demoAdvisor: Advisor = {
  organization: {
    id: "org-demo-1",
    name: "Northbridge Advisory Demo",
    region: "Demo Region",
    trustNote: DEMO_TRUST_BANNER,
  },
  profile: {
    id: "adv-demo-1",
    displayName: "Alex Rivera (Demo)",
    title: "Senior Research Advisor",
    organizationId: "org-demo-1",
    specialties: ["Equity research", "Model portfolios", "Client reviews"],
  },
};

export const demoClients: ClientSummary[] = [
  {
    id: "cli-demo-a",
    alias: "Client Alpha",
    segment: "Growth-oriented household (demo)",
    riskProfile: "growth",
    objectives: ["Long-horizon equity growth", "Education funding overlay"],
    lastTouchAt: "2026-07-18T10:00:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — equity tilt",
    researchHistoryCount: 4,
    reviewStatus: "due_soon",
    portfolioSizeBand: "medium",
    portfolioSizeLabel: "Demo band M",
    meetingDueAt: "2026-07-22T15:00:00.000Z",
    nextReviewAt: "2026-07-22T15:00:00.000Z",
    portfolioHealthLabel: "Stable (demo)",
  },
  {
    id: "cli-demo-b",
    alias: "Client Beta",
    segment: "Balanced institutional sample (demo)",
    riskProfile: "moderate",
    objectives: ["Capital preservation bias", "Income overlay"],
    lastTouchAt: "2026-07-19T14:30:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — balanced",
    researchHistoryCount: 6,
    reviewStatus: "on_track",
    portfolioSizeBand: "institutional",
    portfolioSizeLabel: "Demo band I",
    meetingDueAt: "2026-07-22T17:30:00.000Z",
    nextReviewAt: "2026-08-15T10:00:00.000Z",
    portfolioHealthLabel: "Watch income sleeve (demo)",
  },
  {
    id: "cli-demo-c",
    alias: "Client Gamma",
    segment: "Quality / value exploration (demo)",
    riskProfile: "conservative",
    objectives: ["Drawdown awareness", "Quality compounders watch"],
    lastTouchAt: "2026-07-20T09:15:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — quality",
    researchHistoryCount: 3,
    reviewStatus: "on_track",
    portfolioSizeBand: "small",
    portfolioSizeLabel: "Demo band S",
    meetingDueAt: "2026-07-23T10:00:00.000Z",
    nextReviewAt: "2026-09-01T14:00:00.000Z",
    portfolioHealthLabel: "Healthy (demo)",
  },
  {
    id: "cli-demo-d",
    alias: "Client Delta",
    segment: "Income-focused sample (demo)",
    riskProfile: "moderate",
    objectives: ["Dividend coverage", "Volatility dampening"],
    lastTouchAt: "2026-07-15T16:00:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — income",
    researchHistoryCount: 5,
    reviewStatus: "overdue",
    portfolioSizeBand: "medium",
    portfolioSizeLabel: "Demo band M",
    meetingDueAt: null,
    nextReviewAt: "2026-07-10T12:00:00.000Z",
    portfolioHealthLabel: "Review overdue (demo)",
  },
  {
    id: "cli-demo-e",
    alias: "Client Epsilon",
    segment: "Aggressive growth sample (demo)",
    riskProfile: "aggressive",
    objectives: ["Thematic research interest", "High tracking error tolerance (demo)"],
    lastTouchAt: "2026-07-21T11:45:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — growth",
    researchHistoryCount: 8,
    reviewStatus: "completed",
    portfolioSizeBand: "large",
    portfolioSizeLabel: "Demo band L",
    meetingDueAt: null,
    nextReviewAt: "2026-10-01T09:00:00.000Z",
    portfolioHealthLabel: "Post-review stable (demo)",
  },
  {
    id: "cli-demo-f",
    alias: "Client Zeta",
    segment: "Balanced household sample (demo)",
    riskProfile: "moderate",
    objectives: ["Goals-based framing", "Cash buffer awareness"],
    lastTouchAt: "2026-07-12T08:00:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — balanced light",
    researchHistoryCount: 2,
    reviewStatus: "due_soon",
    portfolioSizeBand: "small",
    portfolioSizeLabel: "Demo band S",
    meetingDueAt: "2026-07-28T11:00:00.000Z",
    nextReviewAt: "2026-07-28T11:00:00.000Z",
    portfolioHealthLabel: "Stable (demo)",
  },
  {
    id: "cli-demo-g",
    alias: "Client Eta",
    segment: "Value exploration (demo)",
    riskProfile: "growth",
    objectives: ["Value factor curiosity", "Research literacy"],
    lastTouchAt: "2026-07-08T13:20:00.000Z",
    portfolioSnapshotLabel: "Demo sleeve — value",
    researchHistoryCount: 7,
    reviewStatus: "on_track",
    portfolioSizeBand: "large",
    portfolioSizeLabel: "Demo band L",
    meetingDueAt: null,
    nextReviewAt: "2026-08-20T15:00:00.000Z",
    portfolioHealthLabel: "Healthy (demo)",
  },
];

export const demoRelationships: ClientRelationship[] = demoClients.map((c) => ({
  clientId: c.id,
  advisorId: demoAdvisor.profile.id,
  since: "2025-01-01",
  role: "primary",
}));

export const demoMeetings: Meeting[] = [
  {
    id: "mtg-1",
    clientId: "cli-demo-a",
    title: "Quarterly review (demo)",
    scheduledAt: "2026-07-22T15:00:00.000Z",
    status: "scheduled",
    agenda: "Objectives check-in · research highlights · model sleeve discussion",
    notesPlaceholder: "Meeting notes are demo placeholders — no real client data.",
    reviewNotes: "Prep pack ready · confirm education overlay narrative.",
    actionItems: ["Share demo research folder", "Confirm next review window"],
  },
  {
    id: "mtg-2",
    clientId: "cli-demo-b",
    title: "Income overlay sync (demo)",
    scheduledAt: "2026-07-22T17:30:00.000Z",
    status: "scheduled",
    agenda: "Income model portfolio · risk band confirmation",
    notesPlaceholder: "Demo notes only.",
    reviewNotes: "Focus on income sleeve vs moderate risk band.",
    actionItems: ["Update income model bookmark"],
  },
  {
    id: "mtg-3",
    clientId: "cli-demo-c",
    title: "Quality watchlist walkthrough (demo)",
    scheduledAt: "2026-07-23T10:00:00.000Z",
    status: "scheduled",
    agenda: "Saved companies · pinned reports",
    notesPlaceholder: "Demo notes only.",
    reviewNotes: "Walk quality collection only — no live trades.",
    actionItems: ["Pin quality glossary"],
  },
  {
    id: "mtg-4",
    clientId: null,
    title: "Internal research stand-up (demo)",
    scheduledAt: "2026-07-21T09:00:00.000Z",
    status: "completed",
    agenda: "Collection hygiene · favorite reports",
    notesPlaceholder: "Completed demo meeting.",
    reviewNotes: "Hygiene complete for demo collections.",
    actionItems: ["Archive stale demo pins"],
  },
  {
    id: "mtg-5",
    clientId: "cli-demo-d",
    title: "Income review (demo)",
    scheduledAt: "2026-07-05T14:00:00.000Z",
    status: "completed",
    agenda: "Dividend coverage discussion",
    notesPlaceholder: "Completed demo notes.",
    reviewNotes: "Client requested follow-up research — demo only.",
    actionItems: ["Schedule overdue review"],
  },
  {
    id: "mtg-6",
    clientId: "cli-demo-e",
    title: "Thematic deep-dive (demo)",
    scheduledAt: "2026-07-01T16:00:00.000Z",
    status: "cancelled",
    agenda: "Cancelled — reschedule later",
    notesPlaceholder: "Cancelled placeholder.",
    reviewNotes: "Reschedule after Epsilon review cycle.",
    actionItems: [],
  },
  {
    id: "mtg-7",
    clientId: "cli-demo-f",
    title: "Goals framing intro (demo)",
    scheduledAt: "2026-07-28T11:00:00.000Z",
    status: "scheduled",
    agenda: "Objectives · cash buffer",
    notesPlaceholder: "Upcoming demo meeting.",
    reviewNotes: "Keep framing research-literacy oriented.",
    actionItems: ["Attach demo balanced sleeve"],
  },
];

export const demoTasks: Task[] = [
  {
    id: "tsk-1",
    title: "Prepare Client Alpha quarterly pack",
    kind: "upcoming_review",
    status: "in_progress",
    priority: "p0",
    dueAt: "2026-07-22T12:00:00.000Z",
    clientId: "cli-demo-a",
    owner: "Alex Rivera (Demo)",
  },
  {
    id: "tsk-2",
    title: "Follow up on Beta income questions",
    kind: "meeting_followup",
    status: "todo",
    priority: "p1",
    dueAt: "2026-07-23T18:00:00.000Z",
    clientId: "cli-demo-b",
    owner: "Alex Rivera (Demo)",
  },
  {
    id: "tsk-3",
    title: "Research request: quality compounders",
    kind: "research_request",
    status: "waiting",
    priority: "p2",
    dueAt: "2026-07-24T16:00:00.000Z",
    clientId: "cli-demo-c",
    owner: "Research Desk (Demo)",
  },
  {
    id: "tsk-4",
    title: "Portfolio review — Delta income sleeve",
    kind: "portfolio_review",
    status: "todo",
    priority: "p0",
    dueAt: "2026-07-25T14:00:00.000Z",
    clientId: "cli-demo-d",
    owner: "Alex Rivera (Demo)",
  },
  {
    id: "tsk-5",
    title: "Pin Epsilon thematic reports",
    kind: "research_request",
    status: "done",
    priority: "p3",
    dueAt: "2026-07-20T12:00:00.000Z",
    clientId: "cli-demo-e",
    owner: "Alex Rivera (Demo)",
  },
  {
    id: "tsk-6",
    title: "Zeta goals framing checklist",
    kind: "meeting_followup",
    status: "in_progress",
    priority: "p2",
    dueAt: "2026-07-27T12:00:00.000Z",
    clientId: "cli-demo-f",
    owner: "Coverage (Demo)",
  },
  {
    id: "tsk-7",
    title: "Eta value screen export",
    kind: "research_request",
    status: "todo",
    priority: "p2",
    dueAt: "2026-07-30T09:00:00.000Z",
    clientId: "cli-demo-g",
    owner: "Research Desk (Demo)",
  },
];

export const demoNotes: ClientNote[] = [
  {
    id: "note-1",
    clientId: "cli-demo-a",
    kind: "pinned",
    title: "Pinned — education overlay",
    body: "Demo note: keep education funding narrative visible in review pack.",
    pinned: true,
    updatedAt: "2026-07-18T10:05:00.000Z",
  },
  {
    id: "note-2",
    clientId: "cli-demo-a",
    kind: "meeting",
    title: "Meeting — Q2 recap",
    body: "Demo meeting note: confirmed growth risk band still appropriate.",
    pinned: false,
    updatedAt: "2026-07-10T15:00:00.000Z",
  },
  {
    id: "note-3",
    clientId: "cli-demo-a",
    kind: "research",
    title: "Research — quality screen interest",
    body: "Demo research note: bookmarked quality collection for next session.",
    pinned: false,
    updatedAt: "2026-07-12T11:00:00.000Z",
  },
  {
    id: "note-4",
    clientId: "cli-demo-b",
    kind: "advisor",
    title: "Advisor — income preference",
    body: "Demo advisor note: prefer income model discussion over aggressive growth.",
    pinned: true,
    updatedAt: "2026-07-19T14:40:00.000Z",
  },
  {
    id: "note-5",
    clientId: "cli-demo-d",
    kind: "advisor",
    title: "Advisor — overdue review",
    body: "Demo advisor note: prioritize Delta review scheduling.",
    pinned: true,
    updatedAt: "2026-07-16T09:00:00.000Z",
  },
  {
    id: "note-6",
    clientId: "cli-demo-c",
    kind: "research",
    title: "Research — drawdown glossary",
    body: "Demo research note: share methodology limitations card.",
    pinned: false,
    updatedAt: "2026-07-20T09:30:00.000Z",
  },
];

export const demoResearchHistory: ResearchHistoryEvent[] = [
  {
    id: "rh-1",
    clientId: "cli-demo-a",
    kind: "company_reviewed",
    label: "Demo Co. Aurora reviewed",
    occurredAt: "2026-07-17T10:00:00.000Z",
  },
  {
    id: "rh-2",
    clientId: "cli-demo-a",
    kind: "report_exported",
    label: "Exported demo Markdown report",
    occurredAt: "2026-07-16T12:00:00.000Z",
  },
  {
    id: "rh-3",
    clientId: "cli-demo-a",
    kind: "portfolio_review",
    label: "Equity tilt sleeve review (demo)",
    occurredAt: "2026-07-10T09:00:00.000Z",
  },
  {
    id: "rh-4",
    clientId: "cli-demo-a",
    kind: "saved_research",
    label: "Saved — Quality Screen folder",
    occurredAt: "2026-07-08T14:00:00.000Z",
  },
  {
    id: "rh-5",
    clientId: "cli-demo-b",
    kind: "company_reviewed",
    label: "Demo Co. Beacon reviewed",
    occurredAt: "2026-07-18T11:00:00.000Z",
  },
  {
    id: "rh-6",
    clientId: "cli-demo-b",
    kind: "report_exported",
    label: "Exported income sleeve memo (demo)",
    occurredAt: "2026-07-15T16:00:00.000Z",
  },
  {
    id: "rh-7",
    clientId: "cli-demo-d",
    kind: "portfolio_review",
    label: "Income sleeve review overdue (demo)",
    occurredAt: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "rh-8",
    clientId: "cli-demo-e",
    kind: "saved_research",
    label: "Saved thematic pins (demo)",
    occurredAt: "2026-07-19T08:00:00.000Z",
  },
];

export const demoModelPortfolios: ModelPortfolio[] = [
  {
    id: "mp-growth",
    name: "Growth",
    style: "growth",
    description: "Demo equity-heavy allocation for illustration only.",
    allocations: [
      { label: "Equities", weightPct: 80 },
      { label: "Fixed income", weightPct: 10 },
      { label: "Cash / other", weightPct: 10 },
    ],
    demoOnly: true,
  },
  {
    id: "mp-balanced",
    name: "Balanced",
    style: "balanced",
    description: "Demo 60/40-style sleeve — not live investments.",
    allocations: [
      { label: "Equities", weightPct: 60 },
      { label: "Fixed income", weightPct: 30 },
      { label: "Cash / other", weightPct: 10 },
    ],
    demoOnly: true,
  },
  {
    id: "mp-income",
    name: "Income",
    style: "income",
    description: "Demo income tilt — illustrative weights only.",
    allocations: [
      { label: "Equities", weightPct: 35 },
      { label: "Fixed income", weightPct: 50 },
      { label: "Cash / other", weightPct: 15 },
    ],
    demoOnly: true,
  },
  {
    id: "mp-value",
    name: "Value",
    style: "value",
    description: "Demo value factor emphasis — not advice.",
    allocations: [
      { label: "Equities", weightPct: 70 },
      { label: "Fixed income", weightPct: 20 },
      { label: "Cash / other", weightPct: 10 },
    ],
    demoOnly: true,
  },
  {
    id: "mp-quality",
    name: "Quality",
    style: "quality",
    description: "Demo quality compounders sleeve.",
    allocations: [
      { label: "Equities", weightPct: 75 },
      { label: "Fixed income", weightPct: 15 },
      { label: "Cash / other", weightPct: 10 },
    ],
    demoOnly: true,
  },
  {
    id: "mp-custom",
    name: "Custom",
    style: "custom",
    description: "Demo custom blend placeholder for advisor workshops.",
    allocations: [
      { label: "Equities", weightPct: 50 },
      { label: "Fixed income", weightPct: 30 },
      { label: "Alternatives (demo)", weightPct: 10 },
      { label: "Cash / other", weightPct: 10 },
    ],
    demoOnly: true,
  },
];

export const demoResearchCollections: ResearchCollection[] = [
  {
    id: "rc-fav",
    name: "Favorite Reports",
    kind: "favorites",
    itemLabels: ["Demo Report — Quality Screen", "Demo Report — Income Sleeve"],
  },
  {
    id: "rc-saved",
    name: "Saved Companies",
    kind: "saved_companies",
    itemLabels: ["Demo Co. Aurora", "Demo Co. Beacon", "Demo Co. Cedar"],
  },
  {
    id: "rc-folder",
    name: "Research Folders",
    kind: "folder",
    itemLabels: ["Q3 Themes (demo)", "Client Alpha prep (demo)", "Income ideas (demo)"],
  },
  {
    id: "rc-pinned",
    name: "Pinned Reports",
    kind: "pinned",
    itemLabels: ["Pinned — Methodology reminder", "Pinned — Risk band glossary"],
  },
];
