from api_platform.api.routers import (
    analysis,
    auth,
    beta_programme,
    comparison,
    composition,
    copilot,
    enterprise,
    enterprise_auth_platform,
    health,
    institutional_admin,
    institutional_auth,
    meta,
    platform,
    reports,
    research_intelligence,
    workflow,
)

__all__ = [
    "analysis",
    "auth",
    "beta_programme",
    "comparison",
    "composition",
    "copilot",
    "enterprise",
    "enterprise_auth_platform",
    "health",
    "institutional_admin",
    "institutional_auth",
    "meta",
    "platform",
    "reports",
    "research_intelligence",
    "workflow",
]
