"""Canonical Financial Statement Domain — public package surface.

Phase 2 / F2.1–F2.7: models + Income / Balance / Cash Flow / Ratio / Trend / Aggregator Intelligence.
No forecasting or valuation integration.
"""

from __future__ import annotations

from financial.balance_sheet import BALANCE_SHEET_FIELDS, BalanceSheet
from financial.cash_flow import CASH_FLOW_FIELDS, CashFlowStatement
from financial.currency import CurrencyCode, CurrencyRef
from financial.engine import FinancialEngine
from financial.exceptions import (
    BalanceAnalysisError,
    CashFlowAnalysisError,
    FinancialError,
    FinancialRatioError,
    FinancialValidationError,
    IncomeAnalysisError,
    TrendAnalysisError,
    FinancialAggregationError,
)
from financial.income_statement import INCOME_STATEMENT_FIELDS, IncomeStatement
from financial.intelligence import (
    AGGREGATOR_RESEARCH_DISCLAIMER,
    BALANCE_RESEARCH_DISCLAIMER,
    CASHFLOW_RESEARCH_DISCLAIMER,
    RATIO_RESEARCH_DISCLAIMER,
    RESEARCH_DISCLAIMER,
    TREND_RESEARCH_DISCLAIMER,
    AggregatedQualityFlag,
    AssetMetrics,
    BalanceAnalysisMetadata,
    BalanceQualityFlag,
    BalanceSheetAnalysis,
    BalanceSheetEngine,
    BalanceTrendSummary,
    BenchmarkClass,
    CapitalAllocationMetrics,
    CashFlowAnalysis,
    CashFlowAnalysisMetadata,
    CashFlowEngine,
    CashFlowQualityFlag,
    CashFlowTrendSummary,
    CashQualityMetrics,
    ConsistencyMetrics,
    EquityMetrics,
    ExpenseMetrics,
    FinancingCashMetrics,
    FinancialAggregationError,
    FinancialAggregatorEngine,
    FinancialAnalysis,
    FinancialAnalysisMetadata,
    FinancialRatioAnalysis,
    FinancialRatioEngine,
    FinancialStatementsHistory,
    FreeCashFlowMetrics,
    GrowthInvestmentClass,
    GrowthMetrics,
    IncomeAnalysisMetadata,
    IncomeStatementAnalysis,
    IncomeStatementEngine,
    InvestingCashMetrics,
    LeverageMetrics,
    LiabilityMetrics,
    LiquidityMetrics,
    MarginMetrics,
    MetricExplanation,
    MetricTrend,
    OperatingCashMetrics,
    OverallFinancialSummary,
    ProfitabilityMetrics,
    QualityFlag,
    RatioAnalysisMetadata,
    RatioMetric,
    RatioQualityFlag,
    RatioTrendSummary,
    RevenueMetrics,
    RevenueTrendClass,
    TrendAnalysis,
    TrendAnalysisMetadata,
    TrendClass,
    TrendConsistencyMetrics,
    TrendDirection,
    TrendEngine,
    TrendQualityFlag,
    TrendSummary,
    WorkingCapitalMetrics,
    build_explanation,
    validate_aggregation_inputs,
    validate_balance_for_analysis,
    validate_cashflow_for_analysis,
    validate_income_for_analysis,
    validate_ratio_inputs,
    validate_trend_history,
)
from financial.metadata import (
    AccountingStandard,
    CompanyMetadata,
    StatementMetadata,
    UnitScale,
)
from financial.models import (
    FINANCIAL_VERSION,
    FinancialSnapshot,
    FinancialStatements,
)
from financial.normalization import (
    FIELD_ALIASES,
    canonicalize_field_name,
    map_raw_fields,
    normalize_snapshot,
    normalize_statements,
    scale_values,
    statements_from_raw,
)
from financial.period import FinancialPeriod, PeriodType
from financial.validation import (
    ValidationResult,
    validate_snapshot,
    validate_statements,
)

__all__ = [
    "ACCOUNTING_STANDARDS",
    "AGGREGATOR_RESEARCH_DISCLAIMER",
    "BALANCE_RESEARCH_DISCLAIMER",
    "BALANCE_SHEET_FIELDS",
    "CASHFLOW_RESEARCH_DISCLAIMER",
    "CASH_FLOW_FIELDS",
    "FIELD_ALIASES",
    "FINANCIAL_VERSION",
    "INCOME_STATEMENT_FIELDS",
    "RATIO_RESEARCH_DISCLAIMER",
    "RESEARCH_DISCLAIMER",
    "TREND_RESEARCH_DISCLAIMER",
    "AccountingStandard",
    "AggregatedQualityFlag",
    "AssetMetrics",
    "BalanceAnalysisError",
    "BalanceAnalysisMetadata",
    "BalanceQualityFlag",
    "BalanceSheet",
    "BalanceSheetAnalysis",
    "BalanceSheetEngine",
    "BalanceTrendSummary",
    "BenchmarkClass",
    "CapitalAllocationMetrics",
    "CashFlowAnalysis",
    "CashFlowAnalysisError",
    "CashFlowAnalysisMetadata",
    "CashFlowEngine",
    "CashFlowQualityFlag",
    "CashFlowStatement",
    "CashFlowTrendSummary",
    "CashQualityMetrics",
    "CompanyMetadata",
    "ConsistencyMetrics",
    "CurrencyCode",
    "CurrencyRef",
    "EquityMetrics",
    "ExpenseMetrics",
    "FinancingCashMetrics",
    "FinancialAggregationError",
    "FinancialAggregatorEngine",
    "FinancialAnalysis",
    "FinancialAnalysisMetadata",
    "FinancialEngine",
    "FinancialError",
    "FinancialRatioAnalysis",
    "FinancialRatioEngine",
    "FinancialRatioError",
    "FinancialPeriod",
    "FinancialSnapshot",
    "FinancialStatements",
    "FinancialStatementsHistory",
    "FinancialValidationError",
    "FreeCashFlowMetrics",
    "GrowthInvestmentClass",
    "GrowthMetrics",
    "IncomeAnalysisError",
    "IncomeAnalysisMetadata",
    "IncomeStatement",
    "IncomeStatementAnalysis",
    "IncomeStatementEngine",
    "InvestingCashMetrics",
    "LeverageMetrics",
    "LiabilityMetrics",
    "LiquidityMetrics",
    "MarginMetrics",
    "MetricExplanation",
    "MetricTrend",
    "OperatingCashMetrics",
    "OverallFinancialSummary",
    "PeriodType",
    "ProfitabilityMetrics",
    "QualityFlag",
    "RatioAnalysisMetadata",
    "RatioMetric",
    "RatioQualityFlag",
    "RatioTrendSummary",
    "RevenueMetrics",
    "RevenueTrendClass",
    "StatementMetadata",
    "TrendAnalysis",
    "TrendAnalysisError",
    "TrendAnalysisMetadata",
    "TrendClass",
    "TrendConsistencyMetrics",
    "TrendDirection",
    "TrendEngine",
    "TrendQualityFlag",
    "TrendSummary",
    "UnitScale",
    "ValidationResult",
    "WorkingCapitalMetrics",
    "build_explanation",
    "canonicalize_field_name",
    "map_raw_fields",
    "normalize_snapshot",
    "normalize_statements",
    "scale_values",
    "statements_from_raw",
    "validate_aggregation_inputs",
    "validate_balance_for_analysis",
    "validate_cashflow_for_analysis",
    "validate_income_for_analysis",
    "validate_ratio_inputs",
    "validate_snapshot",
    "validate_statements",
    "validate_trend_history",
]

__version__ = "0.7.0"

ACCOUNTING_STANDARDS = tuple(AccountingStandard)
