/** EPIC-F001 — Design system catalogue metadata (no runtime UI). */

export const DESIGN_SYSTEM_VERSION = "0.2.0" as const;

export const COMPONENT_CATALOGUE = {
  theme: ["DspThemeProvider", "ThemeSwitcher", "CSS variables", "semantic tokens"],
  typography: ["Typography (display, h1–h6, body, caption, mono)"],
  layout: [
    "Container",
    "Stack",
    "Grid",
    "Flex",
    "Section",
    "Card*",
    "PageLayout",
  ],
  navigation: [
    "Sidebar",
    "SidebarGroup",
    "SidebarItem",
    "Header",
    "Breadcrumb",
    "CommandPalette",
    "UserMenu",
  ],
  forms: [
    "Button",
    "IconButton",
    "Input",
    "PasswordInput",
    "Textarea",
    "Select",
    "MultiSelect",
    "Checkbox",
    "RadioGroup",
    "Switch",
    "Slider",
    "DatePicker",
    "SearchBox",
    "FormField",
    "ValidationMessage",
  ],
  data: [
    "Table",
    "DataGrid",
    "Badge",
    "Avatar",
    "Tag",
    "Chip",
    "Tooltip",
    "Popover",
    "DropdownMenu",
    "Pagination",
    "Tabs",
    "Accordion",
    "TreeView",
  ],
  feedback: [
    "Alert",
    "Toast",
    "Progress",
    "Skeleton",
    "Spinner",
    "EmptyState",
    "ErrorState",
    "SuccessState",
    "LoadingOverlay",
  ],
  dialogs: ["Modal/Dialog", "Drawer", "ConfirmationDialog", "CommandDialog"],
  charts: ["ChartContainer", "ChartThemeWrapper", "ResponsiveWrapper"],
  utilities: [
    "DsIcons",
    "PermissionWrapper",
    "useMediaQuery",
    "useKeyboardShortcut",
    "DsErrorBoundary",
    "LoadingBlock",
  ],
} as const;
