"use client";

/**
 * Institutional Company Workspace — AI Investment Copilot tab.
 *
 * Calls the live backend `/copilot/complete` engine directly — no client-side
 * templating, no invented answers. Scoped to the current ticker via the
 * already-loaded /analyse request/response (market_context only carries the
 * symbol/company/exchange already visible on screen).
 */

import { useEffect, useId, useRef, useState } from "react";
import { useMutation } from "@tanstack/react-query";

import { Button } from "@/components/ds";
import { api } from "@/lib/api/client";
import type { AnalyseRequest, AnalyseResponse } from "@/lib/api/compositionTypes";
import { ApiClientError } from "@/lib/api/types";
import { useAuth } from "@/lib/auth/AuthProvider";
import { SUGGESTED_QUESTIONS } from "@/lib/copilot/questions";
import type { SuggestedQuestionId } from "@/lib/copilot/types";
import type { ResearchView } from "@/lib/research/mapResearchView";
import { SectionCard } from "../WorkspacePrimitives";

type ChatEntry = {
  id: string;
  role: "user" | "assistant" | "system";
  text: string;
  citations?: string[];
  limitations?: string[];
  unavailable?: boolean;
};

function describeError(error: unknown): string {
  if (error instanceof ApiClientError) {
    if (error.status === 401) {
      return "Permission denied — sign in required for the AI Copilot.";
    }
    return error.message || `API error (${error.status})`;
  }
  if (error instanceof Error) return error.message;
  return "Data unavailable.";
}

export function AiCopilotSection({
  view,
  analyseRequest,
  analyseResponse,
  seedQuestion,
  presentation = "panel",
}: {
  view: ResearchView;
  analyseRequest: AnalyseRequest | null;
  analyseResponse: AnalyseResponse | null;
  /** Prefills the composer from an "Ask" chip. Never auto-submits. */
  seedQuestion?: string | null;
  /** Drawer copy stays client-facing. The panel variant keeps the workspace card. */
  presentation?: "panel" | "conversation";
}) {
  const { session } = useAuth();
  const token = session?.accessToken ?? null;
  const titleId = useId();
  const [messages, setMessages] = useState<ChatEntry[]>([
    {
      id: "sys-0",
      role: "system",
      text:
        presentation === "conversation"
          ? `Ask about this analysis of ${view.company} (${view.ticker}). Follow-up questions stay tied to the research already loaded.`
          : `Ask the AI Investment Copilot about ${view.company} (${view.ticker}). Answers are generated by the backend copilot engine — not a client-side template.`,
    },
  ]);
  const [draft, setDraft] = useState("");
  const idRef = useRef(0);

  useEffect(() => {
    if (seedQuestion?.trim()) setDraft(seedQuestion);
  }, [seedQuestion]);

  const askMutation = useMutation({
    mutationFn: async (args: { questionId: SuggestedQuestionId | "freeform"; text: string }) => {
      return api.copilotComplete(
        {
          question_id: args.questionId,
          freeform: args.questionId === "freeform" ? args.text : undefined,
          request: analyseRequest,
          response: analyseResponse,
          market_context: {
            ticker: view.ticker,
            company: view.company,
            exchange: view.exchange,
          },
        },
        { token },
      );
    },
    onMutate: (args) => {
      idRef.current += 1;
      setMessages((prev) => [
        ...prev,
        { id: `user-${idRef.current}`, role: "user", text: args.text },
      ]);
    },
    onSuccess: (data) => {
      idRef.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: `asst-${idRef.current}`,
          role: "assistant",
          text: data.content || "Data unavailable.",
          citations: data.citations,
          limitations: data.limitations,
          unavailable: data.unavailable,
        },
      ]);
    },
    onError: (err) => {
      idRef.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: `err-${idRef.current}`,
          role: "assistant",
          text: describeError(err),
          unavailable: true,
        },
      ]);
    },
  });

  const disabled = !analyseResponse || askMutation.isPending;

  function ask(questionId: SuggestedQuestionId | "freeform", text: string) {
    if (!text.trim() || disabled) return;
    askMutation.mutate({ questionId, text });
    if (questionId === "freeform") setDraft("");
  }

  if (presentation === "conversation") {
    const inputId = `${titleId}-ask`;
    return (
      <div className="flex flex-col gap-3">
        {!analyseResponse ? (
          <p className="text-sm text-[var(--muted)]">
            Run an analysis first — questions stay tied to the loaded research.
          </p>
        ) : null}
        <div className="flex flex-wrap gap-1.5" aria-label="Suggested questions">
          {SUGGESTED_QUESTIONS.slice(0, 4).map((q) => (
            <button
              key={q.id}
              type="button"
              disabled={disabled}
              onClick={() => ask(q.id, q.label)}
              className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] px-3 py-1 text-[11px] text-[var(--muted)] hover:text-[var(--fg)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:opacity-50"
            >
              {q.label}
            </button>
          ))}
        </div>
        <div
          role="log"
          aria-live="polite"
          aria-labelledby={titleId}
          className="flex max-h-40 flex-col gap-2.5 overflow-y-auto"
        >
          <h3 id={titleId} className="sr-only">
            Ask DSP conversation
          </h3>
          {messages.map((m) => (
            <div
              key={m.id}
              className={m.role === "user" ? "flex justify-end" : "flex gap-2.5"}
            >
              {m.role !== "user" ? (
                <span
                  aria-hidden
                  className="mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-md bg-[linear-gradient(135deg,#7c6af7,#2dd4bf)] text-[9px] font-bold text-white"
                >
                  D
                </span>
              ) : null}
              <div
                className={
                  m.role === "user"
                    ? "max-w-[76%] rounded-[12px_12px_3px_12px] border border-[var(--border)] bg-[var(--surface-2)] px-3.5 py-2 text-[13px] leading-relaxed text-[var(--fg)]"
                    : "max-w-[76%] rounded-[3px_12px_12px_12px] border border-[var(--border)] bg-[var(--surface-2)] px-3.5 py-2 text-[13px] leading-relaxed text-[var(--fg)]"
                }
              >
                <p className="m-0">{m.text}</p>
                {m.citations?.length ? (
                  <p className="mb-0 mt-1 text-[10px] text-[var(--muted)]">
                    Sources: {m.citations.join(", ")}
                  </p>
                ) : null}
              </div>
            </div>
          ))}
          {askMutation.isPending ? (
            <p className="text-xs text-[var(--muted)]" role="status">
              Reviewing the analysis…
            </p>
          ) : null}
        </div>
        <form
          className="flex items-center gap-2 rounded-[10px] border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2 focus-within:border-[color-mix(in_srgb,var(--c-dsp)_50%,transparent)]"
          onSubmit={(e) => {
            e.preventDefault();
            ask("freeform", draft);
          }}
        >
          <label htmlFor={inputId} className="sr-only">
            Ask about this analysis
          </label>
          <input
            id={inputId}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder="Ask about this analysis…"
            disabled={disabled}
            className="min-h-9 flex-1 bg-transparent text-[13px] text-[var(--fg)] outline-none"
          />
          <button
            type="submit"
            aria-label="Ask"
            disabled={disabled || !draft.trim()}
            className="flex size-7 items-center justify-center rounded-full bg-[var(--c-dsp)] text-sm text-white disabled:bg-[var(--surface)] disabled:text-[var(--muted)]"
          >
            ↑
          </button>
        </form>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <SectionCard
        title="AI Investment Copilot"
        description="Backed by /copilot/complete — the platform's live AI engine. Not a client-side simulation."
      >
        {!analyseResponse ? (
          <p className="text-sm text-[var(--muted)]">
            Run an analysis first — the Copilot explains the loaded research,
            it does not fetch its own data.
          </p>
        ) : null}
        <div className="mb-3 flex flex-wrap gap-2" aria-label="Suggested questions">
          {SUGGESTED_QUESTIONS.map((q) => (
            <Button
              key={q.id}
              size="sm"
              variant="secondary"
              disabled={disabled}
              onClick={() => ask(q.id, q.label)}
            >
              {q.label}
            </Button>
          ))}
        </div>
        <div
          role="log"
          aria-live="polite"
          aria-labelledby={titleId}
          className="max-h-[28rem] space-y-3 overflow-y-auto rounded-[var(--radius-md)] border border-[var(--border)] p-3"
        >
          <h3 id={titleId} className="sr-only">
            Copilot conversation
          </h3>
          {messages.map((m) => (
            <div
              key={m.id}
              className={
                m.role === "user"
                  ? "ml-auto max-w-[85%] rounded-[var(--radius-md)] bg-[var(--accent-soft)] px-3 py-2 text-sm text-[var(--accent)]"
                  : "max-w-[85%] rounded-[var(--radius-md)] border border-[var(--border)] px-3 py-2 text-sm"
              }
            >
              <p>{m.text}</p>
              {m.citations?.length ? (
                <p className="mt-1 text-[10px] text-[var(--muted)]">
                  Citations: {m.citations.join(", ")}
                </p>
              ) : null}
              {m.limitations?.length ? (
                <p className="mt-1 text-[10px] text-[var(--muted)]">
                  {m.limitations.join(" · ")}
                </p>
              ) : null}
            </div>
          ))}
          {askMutation.isPending ? (
            <p className="text-xs text-[var(--muted)]" role="status">
              Copilot is thinking…
            </p>
          ) : null}
        </div>
        <form
          className="mt-3 flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            ask("freeform", draft);
          }}
        >
          <label htmlFor="ai-copilot-input" className="sr-only">
            Ask the AI Investment Copilot
          </label>
          <input
            id="ai-copilot-input"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder='e.g. "Explain the valuation" or "Summarize risks"'
            disabled={disabled}
            className="min-h-11 flex-1 rounded-md border border-[var(--border)] bg-[var(--surface)] px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"
          />
          <Button type="submit" disabled={disabled || !draft.trim()}>
            Ask
          </Button>
        </form>
      </SectionCard>
    </div>
  );
}
