"use client";

/**
 * Institutional Company Workspace — AI Investment Copilot tab.
 *
 * Calls the live backend `/copilot/complete` engine directly — no client-side
 * templating, no invented answers. Scoped to the current ticker via the
 * already-loaded /analyse request/response (market_context only carries the
 * symbol/company/exchange already visible on screen).
 */

import { useId, useRef, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { AlertCircle, HelpCircle } from "lucide-react";

import { Badge } from "@/components/ui/Badge";
import { api } from "@/lib/api/client";
import type { AnalyseRequest, AnalyseResponse } from "@/lib/api/compositionTypes";
import { ApiClientError } from "@/lib/api/types";
import { useAuth } from "@/lib/auth/AuthProvider";
import { SUGGESTED_QUESTIONS } from "@/lib/copilot/questions";
import type { SuggestedQuestionId } from "@/lib/copilot/types";
import type { ResearchView } from "@/lib/research/mapResearchView";
import { SectionCard } from "../WorkspacePrimitives";

type ChatEntry = {
  id: string;
  role: "user" | "assistant" | "system";
  text: string;
  citations?: string[];
  limitations?: string[];
  unavailable?: boolean;
};

function describeError(error: unknown): string {
  if (error instanceof ApiClientError) {
    if (error.status === 401) {
      return "Permission denied — sign in required for the AI Copilot.";
    }
    return error.message || `API error (${error.status})`;
  }
  if (error instanceof Error) return error.message;
  return "Data unavailable.";
}

export function AiCopilotSection({
  view,
  analyseRequest,
  analyseResponse,
}: {
  view: ResearchView;
  analyseRequest: AnalyseRequest | null;
  analyseResponse: AnalyseResponse | null;
}) {
  const { session } = useAuth();
  const token = session?.accessToken ?? null;
  const titleId = useId();
  const [messages, setMessages] = useState<ChatEntry[]>([
    {
      id: "sys-0",
      role: "system",
      text: `Ask the AI Investment Copilot about ${view.company} (${view.ticker}). Answers are generated by the backend copilot engine — not a client-side template.`,
    },
  ]);
  const [draft, setDraft] = useState("");
  const idRef = useRef(0);

  const askMutation = useMutation({
    mutationFn: async (args: { questionId: SuggestedQuestionId | "freeform"; text: string }) => {
      return api.copilotComplete(
        {
          question_id: args.questionId,
          freeform: args.questionId === "freeform" ? args.text : undefined,
          request: analyseRequest,
          response: analyseResponse,
          market_context: {
            ticker: view.ticker,
            company: view.company,
            exchange: view.exchange,
          },
        },
        { token },
      );
    },
    onMutate: (args) => {
      idRef.current += 1;
      setMessages((prev) => [
        ...prev,
        { id: `user-${idRef.current}`, role: "user", text: args.text },
      ]);
    },
    onSuccess: (data) => {
      idRef.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: `asst-${idRef.current}`,
          role: "assistant",
          text: data.content || "Data unavailable.",
          citations: data.citations,
          limitations: data.limitations,
          unavailable: data.unavailable,
        },
      ]);
    },
    onError: (err) => {
      idRef.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: `err-${idRef.current}`,
          role: "assistant",
          text: describeError(err),
          unavailable: true,
        },
      ]);
    },
  });

  const disabled = !analyseResponse || askMutation.isPending;

  function ask(questionId: SuggestedQuestionId | "freeform", text: string) {
    if (!text.trim() || disabled) return;
    askMutation.mutate({ questionId, text });
    if (questionId === "freeform") setDraft("");
  }

  return (
    <div className="space-y-4">
      <SectionCard
        title="AI Investment Copilot"
        description="Backed by /copilot/complete — the platform's live AI engine. Not a client-side simulation."
      >
        {!analyseResponse ? (
          <div className="rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-2)] p-4 text-sm text-[var(--muted)]">
            Run an analysis first — the Copilot explains the loaded research, it does not fetch its own data.
          </div>
        ) : (
          <div className="flex flex-wrap items-center gap-2 pb-2">
            <span className="inline-flex min-h-[32px] items-center gap-1.5 rounded-[var(--radius-sm)] border border-[var(--border)] bg-[var(--surface-2)] px-2.5 py-1 text-xs">
              <span className="text-[var(--muted)]">Active Context:</span>
              <span className="font-semibold text-[var(--fg)]">{view.ticker}</span>
              <span className="text-[var(--muted)]">({view.company})</span>
            </span>
            <Badge tone="neutral">AI Boundary: Deterministic Grounding</Badge>
          </div>
        )}

        <div className="mb-3 space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">
            Suggested Research Questions
          </p>
          <div className="flex flex-wrap gap-2" aria-label="Suggested questions">
            {SUGGESTED_QUESTIONS.map((q) => (
              <button
                key={q.id}
                type="button"
                disabled={disabled}
                onClick={() => ask(q.id, q.label)}
                className="inline-flex min-h-[44px] items-center rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3.5 py-2 text-xs font-medium text-[var(--fg)] hover:border-[var(--accent)] hover:bg-[var(--surface-2)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:opacity-50"
              >
                {q.label}
              </button>
            ))}
          </div>
        </div>

        <div
          role="log"
          aria-live="polite"
          aria-labelledby={titleId}
          className="max-h-[28rem] space-y-3 overflow-y-auto rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] p-4"
        >
          <h3 id={titleId} className="sr-only">
            Copilot conversation
          </h3>
          {messages.map((m) => (
            <div
              key={m.id}
              className={
                m.role === "user"
                  ? "ml-auto max-w-[85%] rounded-[var(--radius-md)] border border-[var(--accent)]/30 bg-[var(--accent-soft)] p-3 text-sm text-[var(--ink)]"
                  : m.role === "system"
                    ? "rounded-[var(--radius-md)] border border-dashed border-[var(--border)] bg-[var(--surface-2)] p-3 text-xs text-[var(--muted)]"
                    : "max-w-[85%] rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-2)] p-3 text-sm text-[var(--fg)]"
              }
            >
              <div className="mb-1 flex items-center justify-between gap-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--muted)]">
                <span>{m.role === "user" ? "Analyst" : m.role === "assistant" ? "DSP Copilot" : "System"}</span>
                {m.unavailable ? <Badge tone="warning">Provider Unavailable</Badge> : null}
              </div>
              <p className="leading-relaxed">{m.text}</p>
              {m.citations?.length ? (
                <div className="mt-2 border-t border-[var(--border)] pt-2 text-[11px] text-[var(--muted)]">
                  <span className="font-semibold text-[var(--fg)]">Evidence Citations:</span> {m.citations.join(", ")}
                </div>
              ) : m.role === "assistant" ? (
                <p className="mt-1 text-[11px] text-[var(--muted)]">Source unavailable: Provider unavailable.</p>
              ) : null}
              {m.limitations?.length ? (
                <p className="mt-1 text-[11px] text-[var(--muted)]">
                  <span className="font-semibold text-[var(--fg)]">Limitations:</span> {m.limitations.join(" · ")}
                </p>
              ) : null}
            </div>
          ))}
          {askMutation.isPending ? (
            <div className="flex items-center gap-2 py-2 text-xs text-[var(--muted)]" role="status">
              <span className="h-2 w-2 animate-pulse rounded-full bg-[var(--accent)]" aria-hidden="true" />
              Copilot is researching session data…
            </div>
          ) : null}
        </div>

        <form
          className="mt-3 flex flex-wrap gap-2 sm:flex-nowrap"
          onSubmit={(e) => {
            e.preventDefault();
            ask("freeform", draft);
          }}
        >
          <label htmlFor="ai-copilot-input" className="sr-only">
            Ask the AI Investment Copilot
          </label>
          <input
            id="ai-copilot-input"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder='e.g. "Explain the valuation" or "Summarize risks"'
            disabled={disabled}
            className="min-h-[44px] min-w-0 flex-1 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 text-sm text-[var(--fg)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"
          />
          <button
            type="submit"
            disabled={disabled || !draft.trim()}
            className="inline-flex min-h-[44px] min-w-[80px] items-center justify-center rounded-[var(--radius-md)] bg-[var(--accent)] px-4 text-xs font-semibold text-white hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:opacity-50"
          >
            Ask
          </button>
        </form>
      </SectionCard>
    </div>
  );
}
